const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Button,
		C3.Behaviors.solid,
		C3.Plugins.Sprite,
		C3.Plugins.SVGPicture,
		C3.Plugins.Text,
		C3.Behaviors.EightDir,
		C3.Behaviors.bound,
		C3.Behaviors.Turret,
		C3.Behaviors.wrap,
		C3.Plugins.Keyboard,
		C3.Behaviors.Sin,
		C3.Behaviors.Bullet,
		C3.Plugins.Button.Cnds.OnClicked,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.Keyboard.Cnds.OnKey,
		C3.Plugins.Sprite.Acts.Spawn,
		C3.Plugins.Sprite.Acts.SetAngle,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Behaviors.Turret.Cnds.OnTargetAcquired,
		C3.Plugins.Sprite.Acts.AddRemoveAnimation,
		C3.Behaviors.Turret.Cnds.OnShoot,
		C3.Plugins.System.Acts.CreateObject
	];
};
self.C3_JsPropNameTable = [
	{Sólido: 0},
	{Botão: 0},
	{Sprite: 0},
	{Botão2: 0},
	{Sprite2: 0},
	{Sprite3: 0},
	{Sprite4: 0},
	{ImagemSVG: 0},
	{Sprite5: 0},
	{Sprite6: 0},
	{texto: 0},
	{Texto2: 0},
	{Botão3: 0},
	{Sprite7: 0},
	{Sprite8: 0},
	{"8Direções": 0},
	{RestritoAoLayout: 0},
	{Canhão: 0},
	{DarAVolta: 0},
	{naveEspacial: 0},
	{Teclado: 0},
	{Senóide: 0},
	{Sprite10: 0},
	{Sprite11: 0},
	{Botão4: 0},
	{Sprite12: 0},
	{Botão5: 0},
	{Sprite13: 0},
	{Sprite14: 0},
	{Projétil: 0},
	{Sprite15: 0},
	{Sprite9: 0}
];

self.InstanceType = {
	Botão: class extends self.IButtonInstance {},
	Sprite: class extends self.ISpriteInstance {},
	Botão2: class extends self.IButtonInstance {},
	Sprite2: class extends self.ISpriteInstance {},
	Sprite3: class extends self.ISpriteInstance {},
	Sprite4: class extends self.ISpriteInstance {},
	ImagemSVG: class extends self.ISVGPictureInstance {},
	Sprite5: class extends self.ISpriteInstance {},
	Sprite6: class extends self.ISpriteInstance {},
	texto: class extends self.ITextInstance {},
	Texto2: class extends self.ITextInstance {},
	Botão3: class extends self.IButtonInstance {},
	Sprite7: class extends self.ISpriteInstance {},
	Sprite8: class extends self.ISpriteInstance {},
	naveEspacial: class extends self.ISpriteInstance {},
	Teclado: class extends self.IInstance {},
	Sprite10: class extends self.ISpriteInstance {},
	Sprite11: class extends self.ISpriteInstance {},
	Botão4: class extends self.IButtonInstance {},
	Sprite12: class extends self.ISpriteInstance {},
	Botão5: class extends self.IButtonInstance {},
	Sprite13: class extends self.ISpriteInstance {},
	Sprite14: class extends self.ISpriteInstance {},
	Sprite15: class extends self.ISpriteInstance {},
	Sprite9: class extends self.ISpriteInstance {}
}