const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Plugins.Text,
		C3.Plugins.Button,
		C3.Behaviors.scrollto,
		C3.Behaviors.Platform,
		C3.Behaviors.solid,
		C3.Plugins.Mouse,
		C3.Plugins.Camera3D,
		C3.Plugins.Button.Cnds.OnClicked,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.Mouse.Cnds.OnObjectClicked
	];
};
self.C3_JsPropNameTable = [
	{Sprite: 0},
	{Texto: 0},
	{Botão: 0},
	{TUTORIAL: 0},
	{HISTÓRIA: 0},
	{Sprite2: 0},
	{Sprite3: 0},
	{vOLTARAOLAYOUT: 0},
	{VOLTARPROLAYOUT: 0},
	{Sprite4: 0},
	{Sprite5: 0},
	{CentrarEm: 0},
	{Plataforma: 0},
	{Sprite6: 0},
	{Sólido: 0},
	{Sprite7: 0},
	{Sprite8: 0},
	{Sprite9: 0},
	{Sprite10: 0},
	{Sprite11: 0},
	{Sprite12: 0},
	{Sprite13: 0},
	{Mouse: 0},
	{Sprite14: 0},
	{Sprite15: 0},
	{Sprite16: 0},
	{Sprite17: 0},
	{PP: 0},
	{portaAberta: 0},
	{Sprite20: 0},
	{Sprite21: 0},
	{Sprite22: 0},
	{Câmera3D: 0},
	{Sprite23: 0},
	{monstro: 0},
	{Sprite25: 0},
	{Botão2: 0},
	{Sprite26: 0},
	{Sprite27: 0},
	{Sprite28: 0},
	{Texto2: 0},
	{Texto3: 0},
	{Sprite29: 0},
	{Botão3: 0},
	{chave: 0},
	{Sprite18: 0},
	{Sprite19: 0},
	{Sprite24: 0},
	{Texto4: 0},
	{Sprite30: 0},
	{Sprite31: 0}
];

self.InstanceType = {
	Sprite: class extends self.ISpriteInstance {},
	Texto: class extends self.ITextInstance {},
	Botão: class extends self.IButtonInstance {},
	TUTORIAL: class extends self.IButtonInstance {},
	HISTÓRIA: class extends self.IButtonInstance {},
	Sprite2: class extends self.ISpriteInstance {},
	Sprite3: class extends self.ISpriteInstance {},
	vOLTARAOLAYOUT: class extends self.IButtonInstance {},
	VOLTARPROLAYOUT: class extends self.IButtonInstance {},
	Sprite4: class extends self.ISpriteInstance {},
	Sprite5: class extends self.ISpriteInstance {},
	Sprite6: class extends self.ISpriteInstance {},
	Sprite7: class extends self.ISpriteInstance {},
	Sprite8: class extends self.ISpriteInstance {},
	Sprite9: class extends self.ISpriteInstance {},
	Sprite10: class extends self.ISpriteInstance {},
	Sprite11: class extends self.ISpriteInstance {},
	Sprite12: class extends self.ISpriteInstance {},
	Sprite13: class extends self.ISpriteInstance {},
	Mouse: class extends self.IInstance {},
	Sprite14: class extends self.ISpriteInstance {},
	Sprite15: class extends self.ISpriteInstance {},
	Sprite16: class extends self.ISpriteInstance {},
	Sprite17: class extends self.ISpriteInstance {},
	PP: class extends self.ISpriteInstance {},
	portaAberta: class extends self.ISpriteInstance {},
	Sprite20: class extends self.ISpriteInstance {},
	Sprite21: class extends self.ISpriteInstance {},
	Sprite22: class extends self.ISpriteInstance {},
	Câmera3D: class extends self.IInstance {},
	Sprite23: class extends self.ISpriteInstance {},
	monstro: class extends self.ISpriteInstance {},
	Sprite25: class extends self.ISpriteInstance {},
	Botão2: class extends self.IButtonInstance {},
	Sprite26: class extends self.ISpriteInstance {},
	Sprite27: class extends self.ISpriteInstance {},
	Sprite28: class extends self.ISpriteInstance {},
	Texto2: class extends self.ITextInstance {},
	Texto3: class extends self.ITextInstance {},
	Sprite29: class extends self.ISpriteInstance {},
	Botão3: class extends self.IButtonInstance {},
	chave: class extends self.ISpriteInstance {},
	Sprite18: class extends self.ISpriteInstance {},
	Sprite19: class extends self.ISpriteInstance {},
	Sprite24: class extends self.ISpriteInstance {},
	Texto4: class extends self.ITextInstance {},
	Sprite30: class extends self.ISpriteInstance {},
	Sprite31: class extends self.ISpriteInstance {}
}