const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Plugins.Text,
		C3.Plugins.Button,
		C3.Behaviors.scrollto,
		C3.Behaviors.Car,
		C3.Behaviors.solid,
		C3.Behaviors.Sin,
		C3.Behaviors.Bullet,
		C3.Plugins.Keyboard,
		C3.Plugins.Mouse,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.Keyboard.Cnds.OnKey,
		C3.Plugins.Sprite.Acts.Spawn,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.Button.Cnds.OnClicked
	];
};
self.C3_JsPropNameTable = [
	{Sprite: 0},
	{anaEElsa: 0},
	{Sprite3: 0},
	{olaf1: 0},
	{Texto: 0},
	{Sprite5: 0},
	{botaoJogar: 0},
	{botaoTutorial: 0},
	{Sprite6: 0},
	{Sprite7: 0},
	{CentrarEm: 0},
	{Carro: 0},
	{olaf2: 0},
	{Sólido: 0},
	{Sprite9: 0},
	{kristoffESven: 0},
	{Senóide: 0},
	{monstro1: 0},
	{Projétil: 0},
	{bolaDeNeve: 0},
	{Teclado: 0},
	{Mouse: 0},
	{Texto2: 0},
	{Texto3: 0},
	{Texto4: 0},
	{Texto5: 0},
	{Sprite2: 0},
	{Sprite4: 0},
	{Sprite8: 0},
	{Sprite10: 0},
	{Texto6: 0},
	{Sprite11: 0},
	{Sprite12: 0},
	{Texto7: 0},
	{Sprite13: 0},
	{Texto8: 0},
	{botaoJogar2: 0},
	{botaovoltar: 0},
	{Sprite14: 0},
	{monstro2: 0},
	{monstro3: 0},
	{monstro4: 0},
	{monstro5: 0},
	{PORTAL: 0},
	{VOLTAR: 0},
	{Texto9: 0},
	{Sprite15: 0}
];

self.InstanceType = {
	Sprite: class extends self.ISpriteInstance {},
	anaEElsa: class extends self.ISpriteInstance {},
	Sprite3: class extends self.ISpriteInstance {},
	olaf1: class extends self.ISpriteInstance {},
	Texto: class extends self.ITextInstance {},
	Sprite5: class extends self.ISpriteInstance {},
	botaoJogar: class extends self.IButtonInstance {},
	botaoTutorial: class extends self.IButtonInstance {},
	Sprite6: class extends self.ISpriteInstance {},
	Sprite7: class extends self.ISpriteInstance {},
	olaf2: class extends self.ISpriteInstance {},
	Sprite9: class extends self.ISpriteInstance {},
	kristoffESven: class extends self.ISpriteInstance {},
	monstro1: class extends self.ISpriteInstance {},
	bolaDeNeve: class extends self.ISpriteInstance {},
	Teclado: class extends self.IInstance {},
	Mouse: class extends self.IInstance {},
	Texto2: class extends self.ITextInstance {},
	Texto3: class extends self.ITextInstance {},
	Texto4: class extends self.ITextInstance {},
	Texto5: class extends self.ITextInstance {},
	Sprite2: class extends self.ISpriteInstance {},
	Sprite4: class extends self.ISpriteInstance {},
	Sprite8: class extends self.ISpriteInstance {},
	Sprite10: class extends self.ISpriteInstance {},
	Texto6: class extends self.ITextInstance {},
	Sprite11: class extends self.ISpriteInstance {},
	Sprite12: class extends self.ISpriteInstance {},
	Texto7: class extends self.ITextInstance {},
	Sprite13: class extends self.ISpriteInstance {},
	Texto8: class extends self.ITextInstance {},
	botaoJogar2: class extends self.IButtonInstance {},
	botaovoltar: class extends self.IButtonInstance {},
	Sprite14: class extends self.ISpriteInstance {},
	monstro2: class extends self.ISpriteInstance {},
	monstro3: class extends self.ISpriteInstance {},
	monstro4: class extends self.ISpriteInstance {},
	monstro5: class extends self.ISpriteInstance {},
	PORTAL: class extends self.ISpriteInstance {},
	VOLTAR: class extends self.IButtonInstance {},
	Texto9: class extends self.ITextInstance {},
	Sprite15: class extends self.ISpriteInstance {}
}