const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Plugins.Text,
		C3.Plugins.Button,
		C3.Behaviors.solid,
		C3.Behaviors.Sin,
		C3.Behaviors.Platform,
		C3.Plugins.TiledBg,
		C3.Plugins.Button.Cnds.OnClicked,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.Sprite.Cnds.IsOutsideLayout,
		C3.Plugins.Sprite.Acts.SetPos,
		C3.Plugins.Sprite.Cnds.OnCollision
	];
};
self.C3_JsPropNameTable = [
	{Sprite: 0},
	{Texto: 0},
	{JOGAR: 0},
	{TUTORIAL: 0},
	{Sprite2: 0},
	{Textotutorial: 0},
	{VOLTARPARATELAINICIAL: 0},
	{Sprite3: 0},
	{Sprite4: 0},
	{Sprite5: 0},
	{Sprite6: 0},
	{Sprite7: 0},
	{Sólido: 0},
	{Senóide: 0},
	{Sprite8: 0},
	{Plataforma2: 0},
	{Sprite9: 0},
	{PlanoDeFundoEmBlocos: 0},
	{Sprite10: 0},
	{Sprite11: 0},
	{Sprite12: 0},
	{Texto2: 0},
	{voltarproiniciowin: 0},
	{Sprite13: 0},
	{Sprite14: 0},
	{Plataforma: 0},
	{Sprite15: 0},
	{porta2: 0}
];

self.InstanceType = {
	Sprite: class extends self.ISpriteInstance {},
	Texto: class extends self.ITextInstance {},
	JOGAR: class extends self.IButtonInstance {},
	TUTORIAL: class extends self.IButtonInstance {},
	Sprite2: class extends self.ISpriteInstance {},
	Textotutorial: class extends self.ITextInstance {},
	VOLTARPARATELAINICIAL: class extends self.IButtonInstance {},
	Sprite3: class extends self.ISpriteInstance {},
	Sprite4: class extends self.ISpriteInstance {},
	Sprite5: class extends self.ISpriteInstance {},
	Sprite6: class extends self.ISpriteInstance {},
	Sprite7: class extends self.ISpriteInstance {},
	Sprite8: class extends self.ISpriteInstance {},
	Sprite9: class extends self.ISpriteInstance {},
	PlanoDeFundoEmBlocos: class extends self.ITiledBackgroundInstance {},
	Sprite10: class extends self.ISpriteInstance {},
	Sprite11: class extends self.ISpriteInstance {},
	Sprite12: class extends self.ISpriteInstance {},
	Texto2: class extends self.ITextInstance {},
	voltarproiniciowin: class extends self.IButtonInstance {},
	Sprite13: class extends self.ISpriteInstance {},
	Sprite14: class extends self.ISpriteInstance {},
	Sprite15: class extends self.ISpriteInstance {},
	porta2: class extends self.ISpriteInstance {}
}