const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Plugins.Mouse,
		C3.Plugins.Text,
		C3.Behaviors.EightDir,
		C3.Behaviors.Sin,
		C3.Behaviors.solid,
		C3.Plugins.Mouse.Cnds.OnObjectClicked,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.Sprite.Cnds.OnCollision
	];
};
self.C3_JsPropNameTable = [
	{Sprite: 0},
	{Sprite3: 0},
	{Sprite4: 0},
	{Mouse: 0},
	{Sprite2: 0},
	{Sprite5: 0},
	{Texto: 0},
	{Sprite6: 0},
	{Sprite7: 0},
	{"8Direções": 0},
	{pixe: 0},
	{Sprite8: 0},
	{Sprite10: 0},
	{Sprite9: 0},
	{Sprite11: 0},
	{Senóide: 0},
	{Sprite12: 0},
	{Sprite13: 0},
	{Sprite14: 0},
	{Sprite15: 0},
	{Sprite16: 0},
	{Texto2: 0},
	{Texto3: 0},
	{Sprite17: 0},
	{Sprite18: 0},
	{Sprite19: 0},
	{Texto4: 0},
	{Sprite20: 0},
	{Sprite21: 0},
	{Sólido: 0},
	{Sprite22: 0},
	{Sprite23: 0},
	{Sprite24: 0},
	{Texto5: 0}
];

self.InstanceType = {
	Sprite: class extends self.ISpriteInstance {},
	Sprite3: class extends self.ISpriteInstance {},
	Sprite4: class extends self.ISpriteInstance {},
	Mouse: class extends self.IInstance {},
	Sprite2: class extends self.ISpriteInstance {},
	Sprite5: class extends self.ISpriteInstance {},
	Texto: class extends self.ITextInstance {},
	Sprite6: class extends self.ISpriteInstance {},
	Sprite7: class extends self.ISpriteInstance {},
	pixe: class extends self.ISpriteInstance {},
	Sprite8: class extends self.ISpriteInstance {},
	Sprite10: class extends self.ISpriteInstance {},
	Sprite9: class extends self.ISpriteInstance {},
	Sprite11: class extends self.ISpriteInstance {},
	Sprite12: class extends self.ISpriteInstance {},
	Sprite13: class extends self.ISpriteInstance {},
	Sprite14: class extends self.ISpriteInstance {},
	Sprite15: class extends self.ISpriteInstance {},
	Sprite16: class extends self.ISpriteInstance {},
	Texto2: class extends self.ITextInstance {},
	Texto3: class extends self.ITextInstance {},
	Sprite17: class extends self.ISpriteInstance {},
	Sprite18: class extends self.ISpriteInstance {},
	Sprite19: class extends self.ISpriteInstance {},
	Texto4: class extends self.ITextInstance {},
	Sprite20: class extends self.ISpriteInstance {},
	Sprite21: class extends self.ISpriteInstance {},
	Sprite22: class extends self.ISpriteInstance {},
	Sprite23: class extends self.ISpriteInstance {},
	Sprite24: class extends self.ISpriteInstance {},
	Texto5: class extends self.ITextInstance {}
}