const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Behaviors.scrollto,
		C3.Behaviors.solid,
		C3.Behaviors.Platform,
		C3.Behaviors.Sin,
		C3.Behaviors.Bullet,
		C3.Plugins.Keyboard,
		C3.Plugins.Button,
		C3.Plugins.Text,
		C3.Plugins.Keyboard.Cnds.OnKey,
		C3.Plugins.Sprite.Acts.Spawn,
		C3.Plugins.Button.Cnds.OnClicked,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.System.Cnds.Every,
		C3.Plugins.Sprite.Acts.SetMirrored
	];
};
self.C3_JsPropNameTable = [
	{cenario: 0},
	{Picaenhance: 0},
	{cenario2: 0},
	{cenario3: 0},
	{cenario4: 0},
	{boneco: 0},
	{CentrarEm: 0},
	{Sólido: 0},
	{Plataforma: 0},
	{upscalemediatransformed: 0},
	{Sprite: 0},
	{reval: 0},
	{rival: 0},
	{upscalemediatransformed2: 0},
	{Senóide: 0},
	{revalremovebgpreview: 0},
	{rival_2removebgpreview: 0},
	{cenario5: 0},
	{Sprite2: 0},
	{Projétil: 0},
	{imageremovebgpreview: 0},
	{Teclado: 0},
	{gameOver: 0},
	{voltarrr: 0},
	{inicio: 0},
	{iniciar: 0},
	{tutorial: 0},
	{Texto: 0},
	{imageremovebgpreview2: 0},
	{Texto2: 0},
	{imageremovebgpreview3: 0},
	{imageremovebgpreview4: 0},
	{imageremovebgpreview5: 0},
	{Texto3: 0},
	{Texto4: 0},
	{vpltar: 0},
	{imageremovebgpreview6: 0},
	{Sprite3: 0},
	{imageremovebgpreview7: 0},
	{imageremovebgpreview8: 0},
	{victory: 0},
	{voltar22: 0},
	{Sprite4: 0},
	{rival_2removebgpreview2: 0},
	{revalremovebgpreview2: 0}
];

self.InstanceType = {
	cenario: class extends self.ISpriteInstance {},
	Picaenhance: class extends self.ISpriteInstance {},
	cenario2: class extends self.ISpriteInstance {},
	cenario3: class extends self.ISpriteInstance {},
	cenario4: class extends self.ISpriteInstance {},
	boneco: class extends self.ISpriteInstance {},
	upscalemediatransformed: class extends self.ISpriteInstance {},
	Sprite: class extends self.ISpriteInstance {},
	reval: class extends self.ISpriteInstance {},
	rival: class extends self.ISpriteInstance {},
	upscalemediatransformed2: class extends self.ISpriteInstance {},
	revalremovebgpreview: class extends self.ISpriteInstance {},
	rival_2removebgpreview: class extends self.ISpriteInstance {},
	cenario5: class extends self.ISpriteInstance {},
	Sprite2: class extends self.ISpriteInstance {},
	imageremovebgpreview: class extends self.ISpriteInstance {},
	Teclado: class extends self.IInstance {},
	gameOver: class extends self.ISpriteInstance {},
	voltarrr: class extends self.IButtonInstance {},
	inicio: class extends self.ISpriteInstance {},
	iniciar: class extends self.IButtonInstance {},
	tutorial: class extends self.IButtonInstance {},
	Texto: class extends self.ITextInstance {},
	imageremovebgpreview2: class extends self.ISpriteInstance {},
	Texto2: class extends self.ITextInstance {},
	imageremovebgpreview3: class extends self.ISpriteInstance {},
	imageremovebgpreview4: class extends self.ISpriteInstance {},
	imageremovebgpreview5: class extends self.ISpriteInstance {},
	Texto3: class extends self.ITextInstance {},
	Texto4: class extends self.ITextInstance {},
	vpltar: class extends self.IButtonInstance {},
	imageremovebgpreview6: class extends self.ISpriteInstance {},
	Sprite3: class extends self.ISpriteInstance {},
	imageremovebgpreview7: class extends self.ISpriteInstance {},
	imageremovebgpreview8: class extends self.ISpriteInstance {},
	victory: class extends self.ISpriteInstance {},
	voltar22: class extends self.IButtonInstance {},
	Sprite4: class extends self.ISpriteInstance {},
	rival_2removebgpreview2: class extends self.ISpriteInstance {},
	revalremovebgpreview2: class extends self.ISpriteInstance {}
}