const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Plugins.Text,
		C3.Plugins.Button,
		C3.Behaviors.Car,
		C3.Behaviors.solid,
		C3.Plugins.Spritefont2,
		C3.Behaviors.jumpthru,
		C3.Behaviors.Platform,
		C3.Behaviors.Bullet,
		C3.Plugins.Keyboard,
		C3.Behaviors.EightDir,
		C3.Plugins.Button.Cnds.OnClicked,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Plugins.Keyboard.Cnds.OnKey,
		C3.Plugins.Sprite.Acts.Spawn,
		C3.Plugins.Sprite.Acts.Destroy
	];
};
self.C3_JsPropNameTable = [
	{Sprite: 0},
	{Texto: 0},
	{Texto2: 0},
	{BotãoStart: 0},
	{Botão2Tut: 0},
	{Sprite2: 0},
	{Sprite3: 0},
	{Sprite4: 0},
	{Texto3: 0},
	{Texto4: 0},
	{Texto5: 0},
	{Texto6: 0},
	{Texto7: 0},
	{Texto8: 0},
	{Sprite5: 0},
	{Carro: 0},
	{Sprite6: 0},
	{Sprite7: 0},
	{Botão: 0},
	{Sprite8: 0},
	{Botão2Volt: 0},
	{Sprite9: 0},
	{Sprite10: 0},
	{Sólido: 0},
	{Sprite11: 0},
	{Sprite12: 0},
	{Sprite13: 0},
	{Sprite14: 0},
	{FonteDeSprites: 0},
	{Sprite15: 0},
	{Sprite16: 0},
	{Sprite17: 0},
	{Sprite18: 0},
	{Sprite19: 0},
	{Sprite20: 0},
	{Sprite21: 0},
	{Sprite22: 0},
	{Sprite23: 0},
	{Sprite24: 0},
	{Sprite25: 0},
	{Sprite26: 0},
	{Sprite27: 0},
	{FonteDeSprites2: 0},
	{Sprite28: 0},
	{Sprite29: 0},
	{Sprite30: 0},
	{Sprite31: 0},
	{Sprite32: 0},
	{PularAtravés: 0},
	{Plataforma: 0},
	{Sprite33: 0},
	{Projétil: 0},
	{Sprite34: 0},
	{Teclado: 0},
	{Sprite35: 0},
	{Texto9: 0},
	{Botão2perd: 0},
	{Sprite36: 0},
	{Sprite37: 0},
	{Texto10: 0},
	{Texto11: 0},
	{Botão2Volta: 0},
	{Sprite38: 0},
	{Texto12: 0},
	{Texto13: 0},
	{Texto14: 0},
	{Texto15: 0},
	{"8Direções": 0},
	{Sprite39: 0},
	{Sprite40: 0},
	{Botão2Tut2: 0},
	{Botão2tut2volt: 0},
	{Sprite41: 0}
];

self.InstanceType = {
	Sprite: class extends self.ISpriteInstance {},
	Texto: class extends self.ITextInstance {},
	Texto2: class extends self.ITextInstance {},
	BotãoStart: class extends self.IButtonInstance {},
	Botão2Tut: class extends self.IButtonInstance {},
	Sprite2: class extends self.ISpriteInstance {},
	Sprite3: class extends self.ISpriteInstance {},
	Sprite4: class extends self.ISpriteInstance {},
	Texto3: class extends self.ITextInstance {},
	Texto4: class extends self.ITextInstance {},
	Texto5: class extends self.ITextInstance {},
	Texto6: class extends self.ITextInstance {},
	Texto7: class extends self.ITextInstance {},
	Texto8: class extends self.ITextInstance {},
	Sprite5: class extends self.ISpriteInstance {},
	Sprite6: class extends self.ISpriteInstance {},
	Sprite7: class extends self.ISpriteInstance {},
	Botão: class extends self.IButtonInstance {},
	Sprite8: class extends self.ISpriteInstance {},
	Botão2Volt: class extends self.IButtonInstance {},
	Sprite9: class extends self.ISpriteInstance {},
	Sprite10: class extends self.ISpriteInstance {},
	Sprite11: class extends self.ISpriteInstance {},
	Sprite12: class extends self.ISpriteInstance {},
	Sprite13: class extends self.ISpriteInstance {},
	Sprite14: class extends self.ISpriteInstance {},
	FonteDeSprites: class extends self.ISpriteFontInstance {},
	Sprite15: class extends self.ISpriteInstance {},
	Sprite16: class extends self.ISpriteInstance {},
	Sprite17: class extends self.ISpriteInstance {},
	Sprite18: class extends self.ISpriteInstance {},
	Sprite19: class extends self.ISpriteInstance {},
	Sprite20: class extends self.ISpriteInstance {},
	Sprite21: class extends self.ISpriteInstance {},
	Sprite22: class extends self.ISpriteInstance {},
	Sprite23: class extends self.ISpriteInstance {},
	Sprite24: class extends self.ISpriteInstance {},
	Sprite25: class extends self.ISpriteInstance {},
	Sprite26: class extends self.ISpriteInstance {},
	Sprite27: class extends self.ISpriteInstance {},
	FonteDeSprites2: class extends self.ISpriteFontInstance {},
	Sprite28: class extends self.ISpriteInstance {},
	Sprite29: class extends self.ISpriteInstance {},
	Sprite30: class extends self.ISpriteInstance {},
	Sprite31: class extends self.ISpriteInstance {},
	Sprite32: class extends self.ISpriteInstance {},
	Sprite33: class extends self.ISpriteInstance {},
	Sprite34: class extends self.ISpriteInstance {},
	Teclado: class extends self.IInstance {},
	Sprite35: class extends self.ISpriteInstance {},
	Texto9: class extends self.ITextInstance {},
	Botão2perd: class extends self.IButtonInstance {},
	Sprite36: class extends self.ISpriteInstance {},
	Sprite37: class extends self.ISpriteInstance {},
	Texto10: class extends self.ITextInstance {},
	Texto11: class extends self.ITextInstance {},
	Botão2Volta: class extends self.IButtonInstance {},
	Sprite38: class extends self.ISpriteInstance {},
	Texto12: class extends self.ITextInstance {},
	Texto13: class extends self.ITextInstance {},
	Texto14: class extends self.ITextInstance {},
	Texto15: class extends self.ITextInstance {},
	Sprite39: class extends self.ISpriteInstance {},
	Sprite40: class extends self.ISpriteInstance {},
	Botão2Tut2: class extends self.IButtonInstance {},
	Botão2tut2volt: class extends self.IButtonInstance {},
	Sprite41: class extends self.ISpriteInstance {}
}