const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Button,
		C3.Plugins.Sprite,
		C3.Plugins.Text,
		C3.Behaviors.Platform,
		C3.Behaviors.scrollto,
		C3.Plugins.Keyboard,
		C3.Behaviors.solid,
		C3.Plugins.Button.Cnds.OnClicked,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.Keyboard.Cnds.OnAnyKey,
		C3.Plugins.Sprite.Acts.StartAnim,
		C3.Plugins.Sprite.Cnds.OnCollision
	];
};
self.C3_JsPropNameTable = [
	{Botão: 0},
	{cobblestonesseamlesstexturacinzavintageroadpatternforwallpapervectorillustrationofastonebackgroundforgamegraphicdesignvetor: 0},
	{Variável1: 0},
	{Texto: 0},
	{imageremovebgpreview: 0},
	{imageremovebgpreview2: 0},
	{imageremovebgpreview3: 0},
	{Botão2: 0},
	{designdeinterioresdecozinhacommoveis_: 0},
	{imageremovebgpreview4: 0},
	{Plataforma: 0},
	{CentrarEm: 0},
	{imageremovebgpreview5: 0},
	{Sprite: 0},
	{Teclado: 0},
	{imageremovebgpreview6: 0},
	{imageremovebgpreview7: 0},
	{Sólido: 0},
	{Sprite2: 0},
	{Sprite3: 0},
	{Sprite4: 0},
	{Sprite5: 0},
	{imageremovebgpreview8: 0},
	{cobblestonesseamlesstexturacinzavintageroadpatternforwallpapervectorillustrationofastonebackgroundforgamegraphicdesignvetor2: 0},
	{imageremovebgpreview9: 0},
	{imageremovebgpreview10: 0},
	{Texto2: 0},
	{photo162919752063516570fbd0bb: 0},
	{imageremovebgpreview11: 0},
	{photo1690480150509b2306320b11c: 0},
	{Botão3: 0},
	{Botão4: 0},
	{Texto3: 0},
	{Texto4: 0},
	{imageremovebgpreview12: 0},
	{images: 0},
	{Texto5: 0},
	{imageremovebgpreview13: 0},
	{Botão5: 0},
	{Sprite6: 0},
	{Sprite7: 0}
];

self.InstanceType = {
	Botão: class extends self.IButtonInstance {},
	cobblestonesseamlesstexturacinzavintageroadpatternforwallpapervectorillustrationofastonebackgroundforgamegraphicdesignvetor: class extends self.ISpriteInstance {},
	Texto: class extends self.ITextInstance {},
	imageremovebgpreview: class extends self.ISpriteInstance {},
	imageremovebgpreview2: class extends self.ISpriteInstance {},
	imageremovebgpreview3: class extends self.ISpriteInstance {},
	Botão2: class extends self.IButtonInstance {},
	designdeinterioresdecozinhacommoveis_: class extends self.ISpriteInstance {},
	imageremovebgpreview4: class extends self.ISpriteInstance {},
	imageremovebgpreview5: class extends self.ISpriteInstance {},
	Sprite: class extends self.ISpriteInstance {},
	Teclado: class extends self.IInstance {},
	imageremovebgpreview6: class extends self.ISpriteInstance {},
	imageremovebgpreview7: class extends self.ISpriteInstance {},
	Sprite2: class extends self.ISpriteInstance {},
	Sprite3: class extends self.ISpriteInstance {},
	Sprite4: class extends self.ISpriteInstance {},
	Sprite5: class extends self.ISpriteInstance {},
	imageremovebgpreview8: class extends self.ISpriteInstance {},
	cobblestonesseamlesstexturacinzavintageroadpatternforwallpapervectorillustrationofastonebackgroundforgamegraphicdesignvetor2: class extends self.ISpriteInstance {},
	imageremovebgpreview9: class extends self.ISpriteInstance {},
	imageremovebgpreview10: class extends self.ISpriteInstance {},
	Texto2: class extends self.ITextInstance {},
	photo162919752063516570fbd0bb: class extends self.ISpriteInstance {},
	imageremovebgpreview11: class extends self.ISpriteInstance {},
	photo1690480150509b2306320b11c: class extends self.ISpriteInstance {},
	Botão3: class extends self.IButtonInstance {},
	Botão4: class extends self.IButtonInstance {},
	Texto3: class extends self.ITextInstance {},
	Texto4: class extends self.ITextInstance {},
	imageremovebgpreview12: class extends self.ISpriteInstance {},
	images: class extends self.ISpriteInstance {},
	Texto5: class extends self.ITextInstance {},
	imageremovebgpreview13: class extends self.ISpriteInstance {},
	Botão5: class extends self.IButtonInstance {},
	Sprite6: class extends self.ISpriteInstance {},
	Sprite7: class extends self.ISpriteInstance {}
}