const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Button,
		C3.Plugins.Sprite,
		C3.Behaviors.scrollto,
		C3.Behaviors.EightDir,
		C3.Behaviors.TileMovement,
		C3.Plugins.Text,
		C3.Plugins.Mouse,
		C3.Behaviors.solid,
		C3.Plugins.Audio,
		C3.Plugins.video,
		C3.Behaviors.Orbit,
		C3.Plugins.Mouse.Cnds.OnObjectClicked,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Plugins.Sprite.Acts.SetPos,
		C3.Plugins.Sprite.Acts.SetSize,
		C3.Plugins.System.Acts.SaveState,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.Sprite.Acts.SetOpacity,
		C3.Behaviors.scrollto.Cnds.IsEnabled,
		C3.Plugins.System.Acts.SetLayoutScale,
		C3.Plugins.System.Acts.LoadState
	];
};
self.C3_JsPropNameTable = [
	{start: 0},
	{back1: 0},
	{Botão: 0},
	{tutoras: 0},
	{CentrarEm: 0},
	{"8Direções": 0},
	{MovimentoEmGrid: 0},
	{Sprite: 0},
	{Texto: 0},
	{Sprite2: 0},
	{Texto2: 0},
	{Texto3: 0},
	{Texto4: 0},
	{Sprite3: 0},
	{Texto5: 0},
	{Texto6: 0},
	{Sprite4: 0},
	{Sprite5: 0},
	{Sprite6: 0},
	{Sprite7: 0},
	{Sprite8: 0},
	{Sprite9: 0},
	{Sprite10: 0},
	{Sprite11: 0},
	{Sprite12: 0},
	{Sprite13: 0},
	{Sprite14: 0},
	{Sprite15: 0},
	{Mouse: 0},
	{Sprite16: 0},
	{Sprite17: 0},
	{Sprite18: 0},
	{Sprite19: 0},
	{Sprite20: 0},
	{Sólido: 0},
	{BARREIRA1: 0},
	{BARREIRA4: 0},
	{BARREIRA2: 0},
	{BARREIRA3: 0},
	{paredeInicio: 0},
	{parede2: 0},
	{parede5: 0},
	{Sprite28: 0},
	{Sprite29: 0},
	{back2: 0},
	{Sprite31: 0},
	{Sprite32: 0},
	{Áudio: 0},
	{parede7: 0},
	{parede8: 0},
	{Sprite35: 0},
	{Sprite36: 0},
	{paredefinal: 0},
	{Sprite38: 0},
	{parede3: 0},
	{parede4: 0},
	{parede13: 0},
	{parede12: 0},
	{Sprite43: 0},
	{Sprite44: 0},
	{Sprite30: 0},
	{tryAgain: 0},
	{parede11: 0},
	{parede6: 0},
	{parede10: 0},
	{parede9: 0},
	{parede14: 0},
	{parede15: 0},
	{Sprite21: 0},
	{tryAgain2: 0},
	{bolinha: 0},
	{Sprite23: 0},
	{Sprite24: 0},
	{parede8s: 0},
	{Vídeo: 0},
	{Vídeo2: 0},
	{Sprite22: 0},
	{vídeoV: 0},
	{video: 0},
	{Sprite25: 0},
	{Sprite26: 0},
	{zoomtarget: 0},
	{Sprite27: 0},
	{bonus: 0},
	{Sprite33: 0},
	{Sprite34: 0},
	{Sprite37: 0},
	{Sprite39: 0},
	{Órbita: 0},
	{sorriso: 0},
	{Sprite41: 0},
	{parede16: 0},
	{Sprite40: 0}
];

self.InstanceType = {
	start: class extends self.IButtonInstance {},
	back1: class extends self.IButtonInstance {},
	Botão: class extends self.IButtonInstance {},
	tutoras: class extends self.IButtonInstance {},
	Sprite: class extends self.ISpriteInstance {},
	Texto: class extends self.ITextInstance {},
	Sprite2: class extends self.ISpriteInstance {},
	Texto2: class extends self.ITextInstance {},
	Texto3: class extends self.ITextInstance {},
	Texto4: class extends self.ITextInstance {},
	Sprite3: class extends self.ISpriteInstance {},
	Texto5: class extends self.ITextInstance {},
	Texto6: class extends self.ITextInstance {},
	Sprite4: class extends self.ISpriteInstance {},
	Sprite5: class extends self.ISpriteInstance {},
	Sprite6: class extends self.ISpriteInstance {},
	Sprite7: class extends self.ISpriteInstance {},
	Sprite8: class extends self.ISpriteInstance {},
	Sprite9: class extends self.ISpriteInstance {},
	Sprite10: class extends self.ISpriteInstance {},
	Sprite11: class extends self.ISpriteInstance {},
	Sprite12: class extends self.ISpriteInstance {},
	Sprite13: class extends self.ISpriteInstance {},
	Sprite14: class extends self.ISpriteInstance {},
	Sprite15: class extends self.ISpriteInstance {},
	Mouse: class extends self.IInstance {},
	Sprite16: class extends self.ISpriteInstance {},
	Sprite17: class extends self.ISpriteInstance {},
	Sprite18: class extends self.ISpriteInstance {},
	Sprite19: class extends self.ISpriteInstance {},
	Sprite20: class extends self.ISpriteInstance {},
	BARREIRA1: class extends self.ISpriteInstance {},
	BARREIRA4: class extends self.ISpriteInstance {},
	BARREIRA2: class extends self.ISpriteInstance {},
	BARREIRA3: class extends self.ISpriteInstance {},
	paredeInicio: class extends self.ISpriteInstance {},
	parede2: class extends self.ISpriteInstance {},
	parede5: class extends self.ISpriteInstance {},
	Sprite28: class extends self.ISpriteInstance {},
	Sprite29: class extends self.ISpriteInstance {},
	back2: class extends self.ISpriteInstance {},
	Sprite31: class extends self.ISpriteInstance {},
	Sprite32: class extends self.ISpriteInstance {},
	Áudio: class extends self.IInstance {},
	parede7: class extends self.ISpriteInstance {},
	parede8: class extends self.ISpriteInstance {},
	Sprite35: class extends self.ISpriteInstance {},
	Sprite36: class extends self.ISpriteInstance {},
	paredefinal: class extends self.ISpriteInstance {},
	Sprite38: class extends self.ISpriteInstance {},
	parede3: class extends self.ISpriteInstance {},
	parede4: class extends self.ISpriteInstance {},
	parede13: class extends self.ISpriteInstance {},
	parede12: class extends self.ISpriteInstance {},
	Sprite43: class extends self.ISpriteInstance {},
	Sprite44: class extends self.ISpriteInstance {},
	Sprite30: class extends self.ISpriteInstance {},
	tryAgain: class extends self.ISpriteInstance {},
	parede11: class extends self.ISpriteInstance {},
	parede6: class extends self.ISpriteInstance {},
	parede10: class extends self.ISpriteInstance {},
	parede9: class extends self.ISpriteInstance {},
	parede14: class extends self.ISpriteInstance {},
	parede15: class extends self.ISpriteInstance {},
	Sprite21: class extends self.ISpriteInstance {},
	tryAgain2: class extends self.ISpriteInstance {},
	bolinha: class extends self.ISpriteInstance {},
	Sprite23: class extends self.ISpriteInstance {},
	Sprite24: class extends self.ISpriteInstance {},
	parede8s: class extends self.ISpriteInstance {},
	Vídeo: class extends self.IWorldInstance {},
	Vídeo2: class extends self.IWorldInstance {},
	Sprite22: class extends self.ISpriteInstance {},
	vídeoV: class extends self.IWorldInstance {},
	video: class extends self.IWorldInstance {},
	Sprite25: class extends self.ISpriteInstance {},
	Sprite26: class extends self.ISpriteInstance {},
	zoomtarget: class extends self.ISpriteInstance {},
	Sprite27: class extends self.ISpriteInstance {},
	bonus: class extends self.ISpriteInstance {},
	Sprite33: class extends self.ISpriteInstance {},
	Sprite34: class extends self.ISpriteInstance {},
	Sprite37: class extends self.ISpriteInstance {},
	Sprite39: class extends self.ISpriteInstance {},
	sorriso: class extends self.ISpriteInstance {},
	Sprite41: class extends self.ISpriteInstance {},
	parede16: class extends self.ISpriteInstance {},
	Sprite40: class extends self.ISpriteInstance {}
}