const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Plugins.Text,
		C3.Plugins.Mouse,
		C3.Plugins.Button,
		C3.Behaviors.Car,
		C3.Behaviors.solid,
		C3.Plugins.Mouse.Cnds.OnObjectClicked,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.Button.Cnds.OnClicked,
		C3.Plugins.Sprite.Cnds.OnCollision
	];
};
self.C3_JsPropNameTable = [
	{Sprite: 0},
	{Sprite2: 0},
	{Texto: 0},
	{Texto2: 0},
	{Sprite3: 0},
	{Sprite4: 0},
	{Texto3: 0},
	{Sprite5: 0},
	{Mouse: 0},
	{Texto4: 0},
	{TEX22: 0},
	{TEXTO11: 0},
	{Sprite6: 0},
	{Sprite7: 0},
	{Sprite8: 0},
	{Sprite9: 0},
	{Sprite10: 0},
	{Sprite11: 0},
	{Sprite12: 0},
	{Texto5: 0},
	{Texto6: 0},
	{aaaaaaaaaaaaaa: 0},
	{Sprite13: 0},
	{Sprite14: 0},
	{Sprite15: 0},
	{Carro: 0},
	{Sprite16: 0},
	{Sólido: 0},
	{Sprite17: 0},
	{Sprite18: 0},
	{Sprite19: 0},
	{Sprite20: 0},
	{Sprite21: 0},
	{Sprite22: 0},
	{Sprite23: 0},
	{oiu: 0},
	{Sprite24: 0},
	{Botão: 0},
	{Sprite25: 0},
	{Botão2: 0},
	{Sprite26: 0},
	{pou: 0}
];

self.InstanceType = {
	Sprite: class extends self.ISpriteInstance {},
	Sprite2: class extends self.ISpriteInstance {},
	Texto: class extends self.ITextInstance {},
	Texto2: class extends self.ITextInstance {},
	Sprite3: class extends self.ISpriteInstance {},
	Sprite4: class extends self.ISpriteInstance {},
	Texto3: class extends self.ITextInstance {},
	Sprite5: class extends self.ISpriteInstance {},
	Mouse: class extends self.IInstance {},
	Texto4: class extends self.ITextInstance {},
	TEX22: class extends self.ITextInstance {},
	TEXTO11: class extends self.ITextInstance {},
	Sprite6: class extends self.ISpriteInstance {},
	Sprite7: class extends self.ISpriteInstance {},
	Sprite8: class extends self.ISpriteInstance {},
	Sprite9: class extends self.ISpriteInstance {},
	Sprite10: class extends self.ISpriteInstance {},
	Sprite11: class extends self.ISpriteInstance {},
	Sprite12: class extends self.ISpriteInstance {},
	Texto5: class extends self.ITextInstance {},
	Texto6: class extends self.ITextInstance {},
	aaaaaaaaaaaaaa: class extends self.IButtonInstance {},
	Sprite13: class extends self.ISpriteInstance {},
	Sprite14: class extends self.ISpriteInstance {},
	Sprite15: class extends self.ISpriteInstance {},
	Sprite16: class extends self.ISpriteInstance {},
	Sprite17: class extends self.ISpriteInstance {},
	Sprite18: class extends self.ISpriteInstance {},
	Sprite19: class extends self.ISpriteInstance {},
	Sprite20: class extends self.ISpriteInstance {},
	Sprite21: class extends self.ISpriteInstance {},
	Sprite22: class extends self.ISpriteInstance {},
	Sprite23: class extends self.ISpriteInstance {},
	oiu: class extends self.IButtonInstance {},
	Sprite24: class extends self.ISpriteInstance {},
	Botão: class extends self.IButtonInstance {},
	Sprite25: class extends self.ISpriteInstance {},
	Botão2: class extends self.IButtonInstance {},
	Sprite26: class extends self.ISpriteInstance {},
	pou: class extends self.ISpriteInstance {}
}