const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Behaviors.Platform,
		C3.Plugins.Button,
		C3.Plugins.TiledBg,
		C3.Plugins.Text,
		C3.Plugins.Keyboard,
		C3.Behaviors.solid,
		C3.Behaviors.scrollto,
		C3.Plugins.Mouse,
		C3.Behaviors.Rotate,
		C3.Plugins.Button.Cnds.OnClicked,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Plugins.System.Acts.RestartLayout,
		C3.Plugins.System.Acts.SubVar,
		C3.Plugins.System.Acts.NextPrevLayout,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.Text.Acts.SetText,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.System.Acts.ResetEventVar
	];
};
self.C3_JsPropNameTable = [
	{Plataforma: 0},
	{PlayerT: 0},
	{BotãoCo: 0},
	{PlanoDeFundoEmBlocos: 0},
	{Texto: 0},
	{botãoT: 0},
	{Teclado: 0},
	{Texto2: 0},
	{Texto3: 0},
	{Texto4: 0},
	{Sólido: 0},
	{Sprite3: 0},
	{CentrarEm: 0},
	{PlayerJ: 0},
	{Sprite4: 0},
	{Sprite5: 0},
	{Texto5: 0},
	{Mouse: 0},
	{Texto6: 0},
	{Botão3: 0},
	{save: 0},
	{BotãoCt: 0},
	{Texto7: 0},
	{VIDAS: 0},
	{PlanoDeFundoEmBlocos2: 0},
	{Texto8: 0},
	{BotãoGM: 0},
	{BotãoGR: 0},
	{Texto9: 0},
	{Texto10: 0},
	{Girar: 0},
	{Sprite: 0},
	{Texto11: 0},
	{PlanoDeFundoEmBlocos3: 0},
	{jogarNV: 0}
];

self.InstanceType = {
	PlayerT: class extends self.ISpriteInstance {},
	BotãoCo: class extends self.IButtonInstance {},
	PlanoDeFundoEmBlocos: class extends self.ITiledBackgroundInstance {},
	Texto: class extends self.ITextInstance {},
	botãoT: class extends self.IButtonInstance {},
	Teclado: class extends self.IInstance {},
	Texto2: class extends self.ITextInstance {},
	Texto3: class extends self.ITextInstance {},
	Texto4: class extends self.ITextInstance {},
	Sprite3: class extends self.ISpriteInstance {},
	PlayerJ: class extends self.ISpriteInstance {},
	Sprite4: class extends self.ISpriteInstance {},
	Sprite5: class extends self.ISpriteInstance {},
	Texto5: class extends self.ITextInstance {},
	Mouse: class extends self.IInstance {},
	Texto6: class extends self.ITextInstance {},
	Botão3: class extends self.IButtonInstance {},
	save: class extends self.ISpriteInstance {},
	BotãoCt: class extends self.IButtonInstance {},
	Texto7: class extends self.ITextInstance {},
	VIDAS: class extends self.ITextInstance {},
	PlanoDeFundoEmBlocos2: class extends self.ITiledBackgroundInstance {},
	Texto8: class extends self.ITextInstance {},
	BotãoGM: class extends self.IButtonInstance {},
	BotãoGR: class extends self.IButtonInstance {},
	Texto9: class extends self.ITextInstance {},
	Texto10: class extends self.ITextInstance {},
	Sprite: class extends self.ISpriteInstance {},
	Texto11: class extends self.ITextInstance {},
	PlanoDeFundoEmBlocos3: class extends self.ITiledBackgroundInstance {},
	jogarNV: class extends self.IButtonInstance {}
}