const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Button,
		C3.Plugins.TextBox,
		C3.Plugins.Text,
		C3.Plugins.Sprite,
		C3.Behaviors.EightDir,
		C3.Behaviors.solid,
		C3.Behaviors.Sin,
		C3.Behaviors.Physics,
		C3.Plugins.Button.Cnds.OnClicked,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.System.Acts.NextPrevLayout,
		C3.Plugins.Sprite.Cnds.OnAnimFinished,
		C3.Plugins.Sprite.Cnds.OnCollision
	];
};
self.C3_JsPropNameTable = [
	{Botão: 0},
	{EntradaDeTexto: 0},
	{Botão2: 0},
	{Texto: 0},
	{Texto2: 0},
	{Texto3: 0},
	{Texto4: 0},
	{Botão3: 0},
	{Botão4: 0},
	{Sprite: 0},
	{Sprite2: 0},
	{"8Direções": 0},
	{Sprite3: 0},
	{Sólido: 0},
	{Sprite4: 0},
	{Senóide: 0},
	{Sprite5: 0},
	{Física: 0},
	{Sprite6: 0},
	{Sprite7: 0},
	{Sprite8: 0},
	{Sprite9: 0},
	{Sprite10: 0},
	{Sprite11: 0},
	{Sprite12: 0},
	{gameOver: 0},
	{Sprite14: 0},
	{Botão5: 0},
	{Sprite13: 0},
	{Sprite15: 0},
	{Botão6: 0}
];

self.InstanceType = {
	Botão: class extends self.IButtonInstance {},
	EntradaDeTexto: class extends self.ITextInputInstance {},
	Botão2: class extends self.IButtonInstance {},
	Texto: class extends self.ITextInstance {},
	Texto2: class extends self.ITextInstance {},
	Texto3: class extends self.ITextInstance {},
	Texto4: class extends self.ITextInstance {},
	Botão3: class extends self.IButtonInstance {},
	Botão4: class extends self.IButtonInstance {},
	Sprite: class extends self.ISpriteInstance {},
	Sprite2: class extends self.ISpriteInstance {},
	Sprite3: class extends self.ISpriteInstance {},
	Sprite4: class extends self.ISpriteInstance {},
	Sprite5: class extends self.ISpriteInstance {},
	Sprite6: class extends self.ISpriteInstance {},
	Sprite7: class extends self.ISpriteInstance {},
	Sprite8: class extends self.ISpriteInstance {},
	Sprite9: class extends self.ISpriteInstance {},
	Sprite10: class extends self.ISpriteInstance {},
	Sprite11: class extends self.ISpriteInstance {},
	Sprite12: class extends self.ISpriteInstance {},
	gameOver: class extends self.ISpriteInstance {},
	Sprite14: class extends self.ISpriteInstance {},
	Botão5: class extends self.IButtonInstance {},
	Sprite13: class extends self.ISpriteInstance {},
	Sprite15: class extends self.ISpriteInstance {},
	Botão6: class extends self.IButtonInstance {}
}