const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Plugins.Text,
		C3.Behaviors.Bullet,
		C3.Plugins.Button,
		C3.Plugins.Keyboard,
		C3.Plugins.Mouse,
		C3.Behaviors.EightDir,
		C3.Behaviors.solid,
		C3.Behaviors.Sin,
		C3.Behaviors.Orbit,
		C3.Plugins.Button.Cnds.OnClicked,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.Keyboard.Cnds.OnKey,
		C3.Plugins.Sprite.Acts.Spawn,
		C3.Plugins.Sprite.Cnds.OnCollision
	];
};
self.C3_JsPropNameTable = [
	{Sprite: 0},
	{Texto: 0},
	{Sprite2: 0},
	{Texto2: 0},
	{Projétil: 0},
	{Sprite3: 0},
	{Sprite4: 0},
	{Sprite5: 0},
	{Botão: 0},
	{Teclado: 0},
	{imagesremovebgpreview: 0},
	{Botão2: 0},
	{Mouse: 0},
	{"8Direções": 0},
	{imagesremovebgpreview2: 0},
	{Sólido: 0},
	{Sprite6: 0},
	{Senóide: 0},
	{Sprite7: 0},
	{Órbita: 0},
	{Sprite8: 0},
	{artedejogo2dpaisagemnaturalparajogosaplicativosmóveisecomputadoresilustraçãovetorial: 0},
	{artedejogo2dpaisagemnaturalparajogosaplicativosmóveisecomputadoresilustraçãovetorialremovebgpreview: 0},
	{Sprite9: 0},
	{Sprite10: 0},
	{Sprite11: 0},
	{pngtreethunderouscongratulationsyouwintextyellowwinorangevectorpngimage_27237648removebgpreview: 0},
	{Botão3: 0},
	{Sprite12: 0},
	{Sprite13: 0},
	{Botão4: 0},
	{Botão5: 0}
];

self.InstanceType = {
	Sprite: class extends self.ISpriteInstance {},
	Texto: class extends self.ITextInstance {},
	Sprite2: class extends self.ISpriteInstance {},
	Texto2: class extends self.ITextInstance {},
	Sprite3: class extends self.ISpriteInstance {},
	Sprite4: class extends self.ISpriteInstance {},
	Sprite5: class extends self.ISpriteInstance {},
	Botão: class extends self.IButtonInstance {},
	Teclado: class extends self.IInstance {},
	imagesremovebgpreview: class extends self.ISpriteInstance {},
	Botão2: class extends self.IButtonInstance {},
	Mouse: class extends self.IInstance {},
	imagesremovebgpreview2: class extends self.ISpriteInstance {},
	Sprite6: class extends self.ISpriteInstance {},
	Sprite7: class extends self.ISpriteInstance {},
	Sprite8: class extends self.ISpriteInstance {},
	artedejogo2dpaisagemnaturalparajogosaplicativosmóveisecomputadoresilustraçãovetorial: class extends self.ISpriteInstance {},
	artedejogo2dpaisagemnaturalparajogosaplicativosmóveisecomputadoresilustraçãovetorialremovebgpreview: class extends self.ISpriteInstance {},
	Sprite9: class extends self.ISpriteInstance {},
	Sprite10: class extends self.ISpriteInstance {},
	Sprite11: class extends self.ISpriteInstance {},
	pngtreethunderouscongratulationsyouwintextyellowwinorangevectorpngimage_27237648removebgpreview: class extends self.ISpriteInstance {},
	Botão3: class extends self.IButtonInstance {},
	Sprite12: class extends self.ISpriteInstance {},
	Sprite13: class extends self.ISpriteInstance {},
	Botão4: class extends self.IButtonInstance {},
	Botão5: class extends self.IButtonInstance {}
}