const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Button,
		C3.Plugins.Sprite,
		C3.Behaviors.solid,
		C3.Behaviors.EightDir,
		C3.Plugins.Text,
		C3.Behaviors.Sin,
		C3.Behaviors.Bullet,
		C3.Plugins.Mouse,
		C3.Plugins.Button.Cnds.OnClicked,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Plugins.Mouse.Cnds.OnClick,
		C3.Plugins.Sprite.Acts.Spawn,
		C3.Plugins.Sprite.Acts.Destroy
	];
};
self.C3_JsPropNameTable = [
	{Botão: 0},
	{Botão2: 0},
	{Botão3: 0},
	{Sprite: 0},
	{BotaoJogar: 0},
	{Botão4: 0},
	{Sprite2: 0},
	{Sólido: 0},
	{Sprite3: 0},
	{Sprite4: 0},
	{"8Direções": 0},
	{Sprite5: 0},
	{Texto: 0},
	{Sprite6: 0},
	{Botão5: 0},
	{Senóide: 0},
	{Sprite7: 0},
	{Botão6: 0},
	{Botão7: 0},
	{Sprite8: 0},
	{Sprite9: 0},
	{Texto2: 0},
	{Sprite10: 0},
	{Projétil: 0},
	{Sprite11: 0},
	{Mouse: 0},
	{Texto3: 0},
	{Texto4: 0},
	{Sprite12: 0},
	{Texto5: 0}
];

self.InstanceType = {
	Botão: class extends self.IButtonInstance {},
	Botão2: class extends self.IButtonInstance {},
	Botão3: class extends self.IButtonInstance {},
	Sprite: class extends self.ISpriteInstance {},
	BotaoJogar: class extends self.IButtonInstance {},
	Botão4: class extends self.IButtonInstance {},
	Sprite2: class extends self.ISpriteInstance {},
	Sprite3: class extends self.ISpriteInstance {},
	Sprite4: class extends self.ISpriteInstance {},
	Sprite5: class extends self.ISpriteInstance {},
	Texto: class extends self.ITextInstance {},
	Sprite6: class extends self.ISpriteInstance {},
	Botão5: class extends self.IButtonInstance {},
	Sprite7: class extends self.ISpriteInstance {},
	Botão6: class extends self.IButtonInstance {},
	Botão7: class extends self.IButtonInstance {},
	Sprite8: class extends self.ISpriteInstance {},
	Sprite9: class extends self.ISpriteInstance {},
	Texto2: class extends self.ITextInstance {},
	Sprite10: class extends self.ISpriteInstance {},
	Sprite11: class extends self.ISpriteInstance {},
	Mouse: class extends self.IInstance {},
	Texto3: class extends self.ITextInstance {},
	Texto4: class extends self.ITextInstance {},
	Sprite12: class extends self.ISpriteInstance {},
	Texto5: class extends self.ITextInstance {}
}