const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Plugins.Mouse,
		C3.Plugins.Text,
		C3.Plugins.Mouse.Cnds.OnObjectClicked,
		C3.Plugins.System.Acts.GoToLayout
	];
};
self.C3_JsPropNameTable = [
	{Sprite: 0},
	{Mouse: 0},
	{propriedades: 0},
	{Sprite3: 0},
	{Texto: 0},
	{Texto2: 0},
	{Texto3: 0},
	{Texto4: 0},
	{Sprite2: 0},
	{Texto5: 0},
	{Sprite4: 0},
	{Texto6: 0},
	{Sprite5: 0},
	{CORRETA: 0},
	{INCORRETA: 0},
	{CORRETA2: 0},
	{correta3: 0},
	{correta5: 0},
	{Sprite6: 0},
	{Sprite7: 0},
	{Sprite8: 0},
	{Sprite9: 0},
	{Texto7: 0},
	{VOLTAR: 0},
	{Texto8: 0},
	{TUTORIAL: 0},
	{Texto9: 0},
	{Sprite10: 0},
	{Texto10: 0},
	{Sprite11: 0},
	{Texto11: 0},
	{Sprite12: 0},
	{Texto12: 0},
	{correta4: 0},
	{EASTEREGG: 0},
	{Sprite13: 0},
	{Sprite14: 0},
	{Texto13: 0},
	{Texto14: 0}
];

self.InstanceType = {
	Sprite: class extends self.ISpriteInstance {},
	Mouse: class extends self.IInstance {},
	propriedades: class extends self.ITextInstance {},
	Sprite3: class extends self.ISpriteInstance {},
	Texto: class extends self.ITextInstance {},
	Texto2: class extends self.ITextInstance {},
	Texto3: class extends self.ITextInstance {},
	Texto4: class extends self.ITextInstance {},
	Sprite2: class extends self.ISpriteInstance {},
	Texto5: class extends self.ITextInstance {},
	Sprite4: class extends self.ISpriteInstance {},
	Texto6: class extends self.ITextInstance {},
	Sprite5: class extends self.ISpriteInstance {},
	CORRETA: class extends self.ISpriteInstance {},
	INCORRETA: class extends self.ISpriteInstance {},
	CORRETA2: class extends self.ISpriteInstance {},
	correta3: class extends self.ISpriteInstance {},
	correta5: class extends self.ISpriteInstance {},
	Sprite6: class extends self.ISpriteInstance {},
	Sprite7: class extends self.ISpriteInstance {},
	Sprite8: class extends self.ISpriteInstance {},
	Sprite9: class extends self.ISpriteInstance {},
	Texto7: class extends self.ITextInstance {},
	VOLTAR: class extends self.ISpriteInstance {},
	Texto8: class extends self.ITextInstance {},
	TUTORIAL: class extends self.ISpriteInstance {},
	Texto9: class extends self.ITextInstance {},
	Sprite10: class extends self.ISpriteInstance {},
	Texto10: class extends self.ITextInstance {},
	Sprite11: class extends self.ISpriteInstance {},
	Texto11: class extends self.ITextInstance {},
	Sprite12: class extends self.ISpriteInstance {},
	Texto12: class extends self.ITextInstance {},
	correta4: class extends self.ISpriteInstance {},
	EASTEREGG: class extends self.ISpriteInstance {},
	Sprite13: class extends self.ISpriteInstance {},
	Sprite14: class extends self.ISpriteInstance {},
	Texto13: class extends self.ITextInstance {},
	Texto14: class extends self.ITextInstance {}
}