const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Plugins.Text,
		C3.Plugins.Button,
		C3.Plugins.Button.Cnds.OnClicked,
		C3.Plugins.System.Acts.GoToLayout
	];
};
self.C3_JsPropNameTable = [
	{Sprite: 0},
	{botãoInicio: 0},
	{Texto: 0},
	{Sprite3: 0},
	{Texto2: 0},
	{Sprite4: 0},
	{inicio: 0},
	{Texto3: 0},
	{Texto4: 0},
	{A1: 0},
	{Texto5: 0},
	{B1: 0},
	{C1: 0},
	{Texto6: 0},
	{Sprite2: 0},
	{Sprite5: 0},
	{Sprite6: 0},
	{Texto7: 0},
	{A2: 0},
	{B2: 0},
	{C2: 0},
	{Texto8: 0},
	{Texto9: 0},
	{Texto10: 0},
	{Sprite7: 0},
	{Sprite8: 0},
	{Texto11: 0},
	{Texto12: 0},
	{DeNovo: 0},
	{Texto13: 0},
	{A3: 0},
	{B3: 0},
	{C3: 0},
	{Texto14: 0},
	{Texto15: 0},
	{Texto16: 0},
	{Texto17: 0},
	{A4: 0},
	{B4: 0},
	{C4: 0},
	{Texto18: 0},
	{Texto19: 0},
	{Texto20: 0},
	{Texto21: 0},
	{A5: 0},
	{B5: 0},
	{C5: 0},
	{Texto22: 0},
	{Texto23: 0},
	{Texto24: 0},
	{Sprite9: 0},
	{Texto25: 0},
	{Texto26: 0},
	{Sprite10: 0},
	{Texto27: 0},
	{tutorial: 0},
	{deVolta: 0}
];

self.InstanceType = {
	Sprite: class extends self.ISpriteInstance {},
	botãoInicio: class extends self.ISpriteInstance {},
	Texto: class extends self.ITextInstance {},
	Sprite3: class extends self.ISpriteInstance {},
	Texto2: class extends self.ITextInstance {},
	Sprite4: class extends self.ISpriteInstance {},
	inicio: class extends self.IButtonInstance {},
	Texto3: class extends self.ITextInstance {},
	Texto4: class extends self.ITextInstance {},
	A1: class extends self.IButtonInstance {},
	Texto5: class extends self.ITextInstance {},
	B1: class extends self.IButtonInstance {},
	C1: class extends self.IButtonInstance {},
	Texto6: class extends self.ITextInstance {},
	Sprite2: class extends self.ISpriteInstance {},
	Sprite5: class extends self.ISpriteInstance {},
	Sprite6: class extends self.ISpriteInstance {},
	Texto7: class extends self.ITextInstance {},
	A2: class extends self.IButtonInstance {},
	B2: class extends self.IButtonInstance {},
	C2: class extends self.IButtonInstance {},
	Texto8: class extends self.ITextInstance {},
	Texto9: class extends self.ITextInstance {},
	Texto10: class extends self.ITextInstance {},
	Sprite7: class extends self.ISpriteInstance {},
	Sprite8: class extends self.ISpriteInstance {},
	Texto11: class extends self.ITextInstance {},
	Texto12: class extends self.ITextInstance {},
	DeNovo: class extends self.IButtonInstance {},
	Texto13: class extends self.ITextInstance {},
	A3: class extends self.IButtonInstance {},
	B3: class extends self.IButtonInstance {},
	C3: class extends self.IButtonInstance {},
	Texto14: class extends self.ITextInstance {},
	Texto15: class extends self.ITextInstance {},
	Texto16: class extends self.ITextInstance {},
	Texto17: class extends self.ITextInstance {},
	A4: class extends self.IButtonInstance {},
	B4: class extends self.IButtonInstance {},
	C4: class extends self.IButtonInstance {},
	Texto18: class extends self.ITextInstance {},
	Texto19: class extends self.ITextInstance {},
	Texto20: class extends self.ITextInstance {},
	Texto21: class extends self.ITextInstance {},
	A5: class extends self.IButtonInstance {},
	B5: class extends self.IButtonInstance {},
	C5: class extends self.IButtonInstance {},
	Texto22: class extends self.ITextInstance {},
	Texto23: class extends self.ITextInstance {},
	Texto24: class extends self.ITextInstance {},
	Sprite9: class extends self.ISpriteInstance {},
	Texto25: class extends self.ITextInstance {},
	Texto26: class extends self.ITextInstance {},
	Sprite10: class extends self.ISpriteInstance {},
	Texto27: class extends self.ITextInstance {},
	tutorial: class extends self.IButtonInstance {},
	deVolta: class extends self.IButtonInstance {}
}