const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Plugins.Text,
		C3.Behaviors.Platform,
		C3.Behaviors.scrollto,
		C3.Behaviors.solid,
		C3.Plugins.Button,
		C3.Plugins.Button.Cnds.OnClicked,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.Sprite.Cnds.OnCollision
	];
};
self.C3_JsPropNameTable = [
	{Sprite3: 0},
	{Sprite4: 0},
	{Sprite5: 0},
	{TextoStart: 0},
	{TextoTutorial: 0},
	{Sprite6: 0},
	{Sprite7: 0},
	{Texto: 0},
	{Sprite8: 0},
	{TextoVoltar: 0},
	{Sprite9: 0},
	{Sprite: 0},
	{Plataforma: 0},
	{CentrarEm: 0},
	{Sprite2: 0},
	{Sprite10: 0},
	{Sólido: 0},
	{Sprite11: 0},
	{Sprite12: 0},
	{Sprite13: 0},
	{Sprite14: 0},
	{Sprite15: 0},
	{Texto2: 0},
	{Sprite16: 0},
	{Texto3Morreu: 0},
	{player: 0},
	{tutorial: 0},
	{voltar: 0},
	{textTutorial: 0},
	{Sprite17: 0},
	{Texto3: 0}
];

self.InstanceType = {
	Sprite3: class extends self.ISpriteInstance {},
	Sprite4: class extends self.ISpriteInstance {},
	Sprite5: class extends self.ISpriteInstance {},
	TextoStart: class extends self.ITextInstance {},
	TextoTutorial: class extends self.ITextInstance {},
	Sprite6: class extends self.ISpriteInstance {},
	Sprite7: class extends self.ISpriteInstance {},
	Texto: class extends self.ITextInstance {},
	Sprite8: class extends self.ISpriteInstance {},
	TextoVoltar: class extends self.ITextInstance {},
	Sprite9: class extends self.ISpriteInstance {},
	Sprite: class extends self.ISpriteInstance {},
	Sprite2: class extends self.ISpriteInstance {},
	Sprite10: class extends self.ISpriteInstance {},
	Sprite11: class extends self.ISpriteInstance {},
	Sprite12: class extends self.ISpriteInstance {},
	Sprite13: class extends self.ISpriteInstance {},
	Sprite14: class extends self.ISpriteInstance {},
	Sprite15: class extends self.ISpriteInstance {},
	Texto2: class extends self.ITextInstance {},
	Sprite16: class extends self.ISpriteInstance {},
	Texto3Morreu: class extends self.ITextInstance {},
	player: class extends self.IButtonInstance {},
	tutorial: class extends self.IButtonInstance {},
	voltar: class extends self.IButtonInstance {},
	textTutorial: class extends self.ITextInstance {},
	Sprite17: class extends self.ISpriteInstance {},
	Texto3: class extends self.ITextInstance {}
}