const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Plugins.Text,
		C3.Plugins.Button,
		C3.Plugins.Mouse,
		C3.Plugins.Spritefont2,
		C3.Plugins.Mouse.Cnds.OnObjectClicked,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.Button.Cnds.OnClicked
	];
};
self.C3_JsPropNameTable = [
	{Sprite: 0},
	{Texto: 0},
	{Sprite2: 0},
	{Botão: 0},
	{Sprite3: 0},
	{Sprite4: 0},
	{Sprite5: 0},
	{Sprite6: 0},
	{Mouse: 0},
	{Sprite7: 0},
	{Sprite8: 0},
	{Sprite9: 0},
	{Sprite10: 0},
	{Sprite11: 0},
	{Texto2: 0},
	{A: 0},
	{C: 0},
	{Texto5: 0},
	{Sprite12: 0},
	{Botão2: 0},
	{A2: 0},
	{Texto3: 0},
	{Texto4: 0},
	{texto11: 0},
	{Sprite13: 0},
	{Texto7: 0},
	{Sprite14: 0},
	{Texto8: 0},
	{Texto9: 0},
	{Sprite15: 0},
	{Texto10: 0},
	{Texto6: 0},
	{Texto12: 0},
	{Texto13: 0},
	{Botão3: 0},
	{Botão4: 0},
	{FonteDeSprites: 0},
	{Sprite16: 0},
	{Texto14: 0},
	{Botão5: 0},
	{Texto15: 0},
	{Sprite17: 0},
	{Sprite18: 0},
	{Texto16: 0},
	{Botão6: 0},
	{Texto17: 0}
];

self.InstanceType = {
	Sprite: class extends self.ISpriteInstance {},
	Texto: class extends self.ITextInstance {},
	Sprite2: class extends self.ISpriteInstance {},
	Botão: class extends self.IButtonInstance {},
	Sprite3: class extends self.ISpriteInstance {},
	Sprite4: class extends self.ISpriteInstance {},
	Sprite5: class extends self.ISpriteInstance {},
	Sprite6: class extends self.ISpriteInstance {},
	Mouse: class extends self.IInstance {},
	Sprite7: class extends self.ISpriteInstance {},
	Sprite8: class extends self.ISpriteInstance {},
	Sprite9: class extends self.ISpriteInstance {},
	Sprite10: class extends self.ISpriteInstance {},
	Sprite11: class extends self.ISpriteInstance {},
	Texto2: class extends self.ITextInstance {},
	A: class extends self.ITextInstance {},
	C: class extends self.ITextInstance {},
	Texto5: class extends self.ITextInstance {},
	Sprite12: class extends self.ISpriteInstance {},
	Botão2: class extends self.IButtonInstance {},
	A2: class extends self.ITextInstance {},
	Texto3: class extends self.ITextInstance {},
	Texto4: class extends self.ITextInstance {},
	texto11: class extends self.ITextInstance {},
	Sprite13: class extends self.ISpriteInstance {},
	Texto7: class extends self.ITextInstance {},
	Sprite14: class extends self.ISpriteInstance {},
	Texto8: class extends self.ITextInstance {},
	Texto9: class extends self.ITextInstance {},
	Sprite15: class extends self.ISpriteInstance {},
	Texto10: class extends self.ITextInstance {},
	Texto6: class extends self.ITextInstance {},
	Texto12: class extends self.ITextInstance {},
	Texto13: class extends self.ITextInstance {},
	Botão3: class extends self.IButtonInstance {},
	Botão4: class extends self.IButtonInstance {},
	FonteDeSprites: class extends self.ISpriteFontInstance {},
	Sprite16: class extends self.ISpriteInstance {},
	Texto14: class extends self.ITextInstance {},
	Botão5: class extends self.IButtonInstance {},
	Texto15: class extends self.ITextInstance {},
	Sprite17: class extends self.ISpriteInstance {},
	Sprite18: class extends self.ISpriteInstance {},
	Texto16: class extends self.ITextInstance {},
	Botão6: class extends self.IButtonInstance {},
	Texto17: class extends self.ITextInstance {}
}