const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Button,
		C3.Plugins.Sprite,
		C3.Plugins.Mouse,
		C3.Plugins.Text,
		C3.Behaviors.solid,
		C3.Plugins.TiledBg,
		C3.Plugins.Spritefont2,
		C3.Behaviors.scrollto,
		C3.Behaviors.Platform,
		C3.Behaviors.Bullet,
		C3.Plugins.Keyboard,
		C3.Plugins.Mouse.Cnds.OnObjectClicked,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Plugins.Keyboard.Cnds.OnKey,
		C3.Plugins.Sprite.Acts.Spawn,
		C3.Plugins.Sprite.Acts.SetAngle
	];
};
self.C3_JsPropNameTable = [
	{Botão: 0},
	{Sprite: 0},
	{Mouse: 0},
	{bolinha1: 0},
	{Sprite5: 0},
	{bolinha2: 0},
	{Texto1: 0},
	{Texto2: 0},
	{Texto3: 0},
	{Sprite2: 0},
	{Sprite3: 0},
	{Sprite4: 0},
	{Sprite6: 0},
	{ceta122: 0},
	{Sprite8: 0},
	{tronco2: 0},
	{Sólido: 0},
	{Sprite9: 0},
	{Sprite10: 0},
	{Sprite11: 0},
	{Sprite12: 0},
	{PlanoDeFundoEmBlocos: 0},
	{PlanoDeFundoEmBlocos2: 0},
	{Sprite13: 0},
	{Texto: 0},
	{Sprite15: 0},
	{Texto4: 0},
	{Texto5: 0},
	{Texto6: 0},
	{Texto7: 0},
	{tronco: 0},
	{troncoDeitado1: 0},
	{Sprite18: 0},
	{tronco4: 0},
	{tronco8: 0},
	{FonteDeSprites: 0},
	{Sprite7: 0},
	{bau10: 0},
	{CentrarEm: 0},
	{Plataforma: 0},
	{cobra12: 0},
	{Sprite14: 0},
	{Sprite19: 0},
	{Sprite20: 0},
	{fogo10: 0},
	{Sprite16: 0},
	{Sprite17: 0},
	{Sprite21: 0},
	{Projétil: 0},
	{Sprite22: 0},
	{Teclado: 0},
	{Sprite23: 0},
	{Sprite24: 0},
	{Sprite25: 0},
	{ceta1104: 0},
	{FonteDeSprites2: 0},
	{Sprite27: 0},
	{Sprite28: 0},
	{Sprite29: 0},
	{Sprite30: 0},
	{Sprite26: 0},
	{Sprite31: 0},
	{Sprite32: 0},
	{Texto8: 0},
	{dinheiro: 0},
	{Sprite33: 0},
	{Sprite34: 0},
	{Sprite35: 0},
	{lenhador11: 0},
	{Sprite36: 0},
	{cobra11: 0},
	{fogo11: 0},
	{lenhador123: 0},
	{Sprite37: 0},
	{Sprite38: 0},
	{Sprite39: 0},
	{Texto9: 0},
	{Sprite40: 0},
	{ceta158: 0},
	{FonteDeSprites3: 0},
	{Sprite41: 0},
	{Sprite42: 0},
	{mama123: 0}
];

self.InstanceType = {
	Botão: class extends self.IButtonInstance {},
	Sprite: class extends self.ISpriteInstance {},
	Mouse: class extends self.IInstance {},
	bolinha1: class extends self.ISpriteInstance {},
	Sprite5: class extends self.ISpriteInstance {},
	bolinha2: class extends self.ISpriteInstance {},
	Texto1: class extends self.ITextInstance {},
	Texto2: class extends self.ITextInstance {},
	Texto3: class extends self.ITextInstance {},
	Sprite2: class extends self.ISpriteInstance {},
	Sprite3: class extends self.ISpriteInstance {},
	Sprite4: class extends self.ISpriteInstance {},
	Sprite6: class extends self.ISpriteInstance {},
	ceta122: class extends self.ISpriteInstance {},
	Sprite8: class extends self.ISpriteInstance {},
	tronco2: class extends self.ISpriteInstance {},
	Sprite9: class extends self.ISpriteInstance {},
	Sprite10: class extends self.ISpriteInstance {},
	Sprite11: class extends self.ISpriteInstance {},
	Sprite12: class extends self.ISpriteInstance {},
	PlanoDeFundoEmBlocos: class extends self.ITiledBackgroundInstance {},
	PlanoDeFundoEmBlocos2: class extends self.ITiledBackgroundInstance {},
	Sprite13: class extends self.ISpriteInstance {},
	Texto: class extends self.ITextInstance {},
	Sprite15: class extends self.ISpriteInstance {},
	Texto4: class extends self.ITextInstance {},
	Texto5: class extends self.ITextInstance {},
	Texto6: class extends self.ITextInstance {},
	Texto7: class extends self.ITextInstance {},
	tronco: class extends self.ISpriteInstance {},
	troncoDeitado1: class extends self.ISpriteInstance {},
	Sprite18: class extends self.ISpriteInstance {},
	tronco4: class extends self.ISpriteInstance {},
	tronco8: class extends self.ISpriteInstance {},
	FonteDeSprites: class extends self.ISpriteFontInstance {},
	Sprite7: class extends self.ISpriteInstance {},
	bau10: class extends self.ISpriteInstance {},
	cobra12: class extends self.ISpriteInstance {},
	Sprite14: class extends self.ISpriteInstance {},
	Sprite19: class extends self.ISpriteInstance {},
	Sprite20: class extends self.ISpriteInstance {},
	fogo10: class extends self.ISpriteInstance {},
	Sprite16: class extends self.ISpriteInstance {},
	Sprite17: class extends self.ISpriteInstance {},
	Sprite21: class extends self.ISpriteInstance {},
	Sprite22: class extends self.ISpriteInstance {},
	Teclado: class extends self.IInstance {},
	Sprite23: class extends self.ISpriteInstance {},
	Sprite24: class extends self.ISpriteInstance {},
	Sprite25: class extends self.ISpriteInstance {},
	ceta1104: class extends self.ISpriteInstance {},
	FonteDeSprites2: class extends self.ISpriteFontInstance {},
	Sprite27: class extends self.ISpriteInstance {},
	Sprite28: class extends self.ISpriteInstance {},
	Sprite29: class extends self.ISpriteInstance {},
	Sprite30: class extends self.ISpriteInstance {},
	Sprite26: class extends self.ISpriteInstance {},
	Sprite31: class extends self.ISpriteInstance {},
	Sprite32: class extends self.ISpriteInstance {},
	Texto8: class extends self.ITextInstance {},
	dinheiro: class extends self.ISpriteInstance {},
	Sprite33: class extends self.ISpriteInstance {},
	Sprite34: class extends self.ISpriteInstance {},
	Sprite35: class extends self.ISpriteInstance {},
	lenhador11: class extends self.ISpriteInstance {},
	Sprite36: class extends self.ISpriteInstance {},
	cobra11: class extends self.ISpriteInstance {},
	fogo11: class extends self.ISpriteInstance {},
	lenhador123: class extends self.ISpriteInstance {},
	Sprite37: class extends self.ISpriteInstance {},
	Sprite38: class extends self.ISpriteInstance {},
	Sprite39: class extends self.ISpriteInstance {},
	Texto9: class extends self.ITextInstance {},
	Sprite40: class extends self.ISpriteInstance {},
	ceta158: class extends self.ISpriteInstance {},
	FonteDeSprites3: class extends self.ISpriteFontInstance {},
	Sprite41: class extends self.ISpriteInstance {},
	Sprite42: class extends self.ISpriteInstance {},
	mama123: class extends self.ISpriteInstance {}
}