const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.TextBox,
		C3.Plugins.Text,
		C3.Plugins.Sprite,
		C3.Behaviors.EightDir,
		C3.Plugins.Button,
		C3.Behaviors.Sin,
		C3.Behaviors.solid,
		C3.Behaviors.Bullet,
		C3.Plugins.Keyboard,
		C3.Plugins.Button.Cnds.OnClicked,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.Keyboard.Cnds.OnKey,
		C3.Plugins.Sprite.Acts.Spawn,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.System.Acts.SetVar
	];
};
self.C3_JsPropNameTable = [
	{EntradaDeTexto: 0},
	{Texto: 0},
	{TERRA: 0},
	{"8Direções": 0},
	{AVIÃO2: 0},
	{INICIO: 0},
	{Texto2: 0},
	{Botão: 0},
	{AVIÃO1: 0},
	{Botão2: 0},
	{TERRA2: 0},
	{Texto3: 0},
	{Senóide: 0},
	{NIMIGOS_Dremovebgpreview: 0},
	{Texto4: 0},
	{Botão3: 0},
	{Texto5: 0},
	{Texto6: 0},
	{Botão4: 0},
	{Texto7: 0},
	{Texto8: 0},
	{trofeuremovebgpreview: 0},
	{Botão5: 0},
	{Sólido: 0},
	{Sprite: 0},
	{Sprite2: 0},
	{Sprite3: 0},
	{Sprite4: 0},
	{Sprite5: 0},
	{Projétil: 0},
	{balaremovebgpreview: 0},
	{Teclado: 0},
	{Variável1: 0}
];

self.InstanceType = {
	EntradaDeTexto: class extends self.ITextInputInstance {},
	Texto: class extends self.ITextInstance {},
	TERRA: class extends self.ISpriteInstance {},
	AVIÃO2: class extends self.ISpriteInstance {},
	INICIO: class extends self.ISpriteInstance {},
	Texto2: class extends self.ITextInstance {},
	Botão: class extends self.IButtonInstance {},
	AVIÃO1: class extends self.ISpriteInstance {},
	Botão2: class extends self.IButtonInstance {},
	TERRA2: class extends self.ISpriteInstance {},
	Texto3: class extends self.ITextInstance {},
	NIMIGOS_Dremovebgpreview: class extends self.ISpriteInstance {},
	Texto4: class extends self.ITextInstance {},
	Botão3: class extends self.IButtonInstance {},
	Texto5: class extends self.ITextInstance {},
	Texto6: class extends self.ITextInstance {},
	Botão4: class extends self.IButtonInstance {},
	Texto7: class extends self.ITextInstance {},
	Texto8: class extends self.ITextInstance {},
	trofeuremovebgpreview: class extends self.ISpriteInstance {},
	Botão5: class extends self.IButtonInstance {},
	Sprite: class extends self.ISpriteInstance {},
	Sprite2: class extends self.ISpriteInstance {},
	Sprite3: class extends self.ISpriteInstance {},
	Sprite4: class extends self.ISpriteInstance {},
	Sprite5: class extends self.ISpriteInstance {},
	balaremovebgpreview: class extends self.ISpriteInstance {},
	Teclado: class extends self.IInstance {}
}