const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Plugins.Text,
		C3.Plugins.Mouse,
		C3.Plugins.Mouse.Cnds.OnObjectClicked,
		C3.Plugins.System.Acts.GoToLayout
	];
};
self.C3_JsPropNameTable = [
	{Sprite: 0},
	{start: 0},
	{Sprite3: 0},
	{Texto: 0},
	{Mouse: 0},
	{Sprite4: 0},
	{Texto2: 0},
	{Texto3: 0},
	{Sprite2: 0},
	{Sprite5: 0},
	{jogartutorial: 0},
	{Texto4: 0},
	{Texto5: 0},
	{Texto6: 0},
	{Sprite6: 0},
	{Sprite7: 0},
	{Texto7: 0},
	{Sprite8: 0},
	{Sprite9: 0},
	{Sprite10: 0},
	{Sprite11: 0},
	{wonerrado: 0},
	{Sprite12: 0},
	{YuanErrado: 0},
	{Texto9: 0},
	{IeneCerto: 0},
	{Sprite13: 0},
	{Texto8: 0},
	{Sprite14: 0},
	{reiniciar: 0},
	{Sprite15: 0},
	{Sprite16: 0},
	{Texto10: 0},
	{Sprite17: 0},
	{Sprite18: 0},
	{Sprite19: 0},
	{Espanholerrado: 0},
	{Mandarimcerto: 0},
	{ArabeErrado: 0},
	{Sprite20: 0},
	{Sprite21: 0},
	{Texto11: 0},
	{Sprite22: 0},
	{Sprite23: 0},
	{Sprite24: 0},
	{"5Errado": 0},
	{"8certo": 0},
	{"10errado": 0},
	{Sprite25: 0},
	{Sprite26: 0},
	{Sprite27: 0},
	{Texto12: 0},
	{Sprite28: 0},
	{Sprite29: 0},
	{Sprite30: 0},
	{indicoerrado: 0},
	{pacificocerto: 0},
	{atlanticoerrado: 0},
	{Sprite31: 0},
	{Sprite32: 0},
	{Sprite33: 0},
	{Texto13: 0},
	{Sprite34: 0},
	{Sprite35: 0},
	{Sprite36: 0},
	{Sprite37: 0},
	{Texto14: 0},
	{africacerto: 0},
	{europaerrado: 0},
	{Asiaerrado: 0},
	{Texto15: 0},
	{Sprite38: 0},
	{Sprite39: 0},
	{Sprite40: 0},
	{micheerrado: 0},
	{vanGogherrado: 0},
	{leocerto: 0},
	{Sprite41: 0},
	{Texto16: 0},
	{Sprite42: 0},
	{Texto17: 0},
	{Sprite43: 0},
	{Sprite44: 0},
	{Sprite45: 0},
	{Sprite46: 0},
	{"3certo": 0},
	{Texto18: 0},
	{"2errado": 0},
	{Texto19: 0},
	{Sprite47: 0},
	{Sprite48: 0},
	{Sprite49: 0},
	{pelecerto: 0},
	{Sprite50: 0},
	{cérebrocerto: 0},
	{Texto20: 0},
	{Texto21: 0},
	{Sprite51: 0},
	{Sprite52: 0},
	{Sprite53: 0},
	{chinaerrado: 0},
	{Françacerto: 0},
	{Texto22: 0},
	{Sprite54: 0},
	{Sprite55: 0},
	{Texto23: 0}
];

self.InstanceType = {
	Sprite: class extends self.ISpriteInstance {},
	start: class extends self.ISpriteInstance {},
	Sprite3: class extends self.ISpriteInstance {},
	Texto: class extends self.ITextInstance {},
	Mouse: class extends self.IInstance {},
	Sprite4: class extends self.ISpriteInstance {},
	Texto2: class extends self.ITextInstance {},
	Texto3: class extends self.ITextInstance {},
	Sprite2: class extends self.ISpriteInstance {},
	Sprite5: class extends self.ISpriteInstance {},
	jogartutorial: class extends self.ISpriteInstance {},
	Texto4: class extends self.ITextInstance {},
	Texto5: class extends self.ITextInstance {},
	Texto6: class extends self.ITextInstance {},
	Sprite6: class extends self.ISpriteInstance {},
	Sprite7: class extends self.ISpriteInstance {},
	Texto7: class extends self.ITextInstance {},
	Sprite8: class extends self.ISpriteInstance {},
	Sprite9: class extends self.ISpriteInstance {},
	Sprite10: class extends self.ISpriteInstance {},
	Sprite11: class extends self.ISpriteInstance {},
	wonerrado: class extends self.ITextInstance {},
	Sprite12: class extends self.ISpriteInstance {},
	YuanErrado: class extends self.ITextInstance {},
	Texto9: class extends self.ITextInstance {},
	IeneCerto: class extends self.ITextInstance {},
	Sprite13: class extends self.ISpriteInstance {},
	Texto8: class extends self.ITextInstance {},
	Sprite14: class extends self.ISpriteInstance {},
	reiniciar: class extends self.ITextInstance {},
	Sprite15: class extends self.ISpriteInstance {},
	Sprite16: class extends self.ISpriteInstance {},
	Texto10: class extends self.ITextInstance {},
	Sprite17: class extends self.ISpriteInstance {},
	Sprite18: class extends self.ISpriteInstance {},
	Sprite19: class extends self.ISpriteInstance {},
	Espanholerrado: class extends self.ITextInstance {},
	Mandarimcerto: class extends self.ITextInstance {},
	ArabeErrado: class extends self.ITextInstance {},
	Sprite20: class extends self.ISpriteInstance {},
	Sprite21: class extends self.ISpriteInstance {},
	Texto11: class extends self.ITextInstance {},
	Sprite22: class extends self.ISpriteInstance {},
	Sprite23: class extends self.ISpriteInstance {},
	Sprite24: class extends self.ISpriteInstance {},
	_5Errado: class extends self.ITextInstance {},
	_8certo: class extends self.ITextInstance {},
	_10errado: class extends self.ITextInstance {},
	Sprite25: class extends self.ISpriteInstance {},
	Sprite26: class extends self.ISpriteInstance {},
	Sprite27: class extends self.ISpriteInstance {},
	Texto12: class extends self.ITextInstance {},
	Sprite28: class extends self.ISpriteInstance {},
	Sprite29: class extends self.ISpriteInstance {},
	Sprite30: class extends self.ISpriteInstance {},
	indicoerrado: class extends self.ITextInstance {},
	pacificocerto: class extends self.ITextInstance {},
	atlanticoerrado: class extends self.ITextInstance {},
	Sprite31: class extends self.ISpriteInstance {},
	Sprite32: class extends self.ISpriteInstance {},
	Sprite33: class extends self.ISpriteInstance {},
	Texto13: class extends self.ITextInstance {},
	Sprite34: class extends self.ISpriteInstance {},
	Sprite35: class extends self.ISpriteInstance {},
	Sprite36: class extends self.ISpriteInstance {},
	Sprite37: class extends self.ISpriteInstance {},
	Texto14: class extends self.ITextInstance {},
	africacerto: class extends self.ITextInstance {},
	europaerrado: class extends self.ITextInstance {},
	Asiaerrado: class extends self.ITextInstance {},
	Texto15: class extends self.ITextInstance {},
	Sprite38: class extends self.ISpriteInstance {},
	Sprite39: class extends self.ISpriteInstance {},
	Sprite40: class extends self.ISpriteInstance {},
	micheerrado: class extends self.ITextInstance {},
	vanGogherrado: class extends self.ITextInstance {},
	leocerto: class extends self.ITextInstance {},
	Sprite41: class extends self.ISpriteInstance {},
	Texto16: class extends self.ITextInstance {},
	Sprite42: class extends self.ISpriteInstance {},
	Texto17: class extends self.ITextInstance {},
	Sprite43: class extends self.ISpriteInstance {},
	Sprite44: class extends self.ISpriteInstance {},
	Sprite45: class extends self.ISpriteInstance {},
	Sprite46: class extends self.ISpriteInstance {},
	_3certo: class extends self.ITextInstance {},
	Texto18: class extends self.ITextInstance {},
	_2errado: class extends self.ITextInstance {},
	Texto19: class extends self.ITextInstance {},
	Sprite47: class extends self.ISpriteInstance {},
	Sprite48: class extends self.ISpriteInstance {},
	Sprite49: class extends self.ISpriteInstance {},
	pelecerto: class extends self.ITextInstance {},
	Sprite50: class extends self.ISpriteInstance {},
	cérebrocerto: class extends self.ITextInstance {},
	Texto20: class extends self.ITextInstance {},
	Texto21: class extends self.ITextInstance {},
	Sprite51: class extends self.ISpriteInstance {},
	Sprite52: class extends self.ISpriteInstance {},
	Sprite53: class extends self.ISpriteInstance {},
	chinaerrado: class extends self.ITextInstance {},
	Françacerto: class extends self.ITextInstance {},
	Texto22: class extends self.ITextInstance {},
	Sprite54: class extends self.ISpriteInstance {},
	Sprite55: class extends self.ISpriteInstance {},
	Texto23: class extends self.ITextInstance {}
}