const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Keyboard,
		C3.Plugins.Mouse,
		C3.Plugins.Sprite,
		C3.Plugins.Text,
		C3.Plugins.Button,
		C3.Behaviors.solid,
		C3.Behaviors.EightDir,
		C3.Behaviors.Sin,
		C3.Behaviors.Bullet,
		C3.Plugins.Mouse.Cnds.OnObjectClicked,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Plugins.System.Cnds.Every,
		C3.Plugins.Sprite.Acts.Spawn,
		C3.Behaviors.Bullet.Acts.SetAngleOfMotion
	];
};
self.C3_JsPropNameTable = [
	{Teclado: 0},
	{Mouse: 0},
	{Sprite: 0},
	{Sprite6: 0},
	{Texto: 0},
	{Botão3: 0},
	{Sprite8: 0},
	{Texto2: 0},
	{Sprite2: 0},
	{Texto3: 0},
	{Sprite3: 0},
	{Sprite4: 0},
	{Sólido: 0},
	{Sprite5: 0},
	{Sprite7: 0},
	{"8Direções": 0},
	{Sprite10: 0},
	{Sprite11: 0},
	{Sprite14: 0},
	{Texto4: 0},
	{Texto5: 0},
	{Texto6: 0},
	{Texto7: 0},
	{Sprite13: 0},
	{Sprite9: 0},
	{Sprite12: 0},
	{Texto8: 0},
	{Sprite17: 0},
	{Sprite19: 0},
	{Sprite15: 0},
	{Texto9: 0},
	{Senóide: 0},
	{Sprite16: 0},
	{Sprite18: 0},
	{Projétil: 0},
	{Sprite20: 0}
];

self.InstanceType = {
	Teclado: class extends self.IInstance {},
	Mouse: class extends self.IInstance {},
	Sprite: class extends self.ISpriteInstance {},
	Sprite6: class extends self.ISpriteInstance {},
	Texto: class extends self.ITextInstance {},
	Botão3: class extends self.IButtonInstance {},
	Sprite8: class extends self.ISpriteInstance {},
	Texto2: class extends self.ITextInstance {},
	Sprite2: class extends self.ISpriteInstance {},
	Texto3: class extends self.ITextInstance {},
	Sprite3: class extends self.ISpriteInstance {},
	Sprite4: class extends self.ISpriteInstance {},
	Sprite5: class extends self.ISpriteInstance {},
	Sprite7: class extends self.ISpriteInstance {},
	Sprite10: class extends self.ISpriteInstance {},
	Sprite11: class extends self.ISpriteInstance {},
	Sprite14: class extends self.ISpriteInstance {},
	Texto4: class extends self.ITextInstance {},
	Texto5: class extends self.ITextInstance {},
	Texto6: class extends self.ITextInstance {},
	Texto7: class extends self.ITextInstance {},
	Sprite13: class extends self.ISpriteInstance {},
	Sprite9: class extends self.ISpriteInstance {},
	Sprite12: class extends self.ISpriteInstance {},
	Texto8: class extends self.ITextInstance {},
	Sprite17: class extends self.ISpriteInstance {},
	Sprite19: class extends self.ISpriteInstance {},
	Sprite15: class extends self.ISpriteInstance {},
	Texto9: class extends self.ITextInstance {},
	Sprite16: class extends self.ISpriteInstance {},
	Sprite18: class extends self.ISpriteInstance {},
	Sprite20: class extends self.ISpriteInstance {}
}