const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Plugins.Button,
		C3.Behaviors.solid,
		C3.Behaviors.Platform,
		C3.Plugins.Keyboard,
		C3.Plugins.Text,
		C3.Behaviors.Sin,
		C3.Plugins.Button.Cnds.OnClicked,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.Keyboard.Cnds.OnKey,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Plugins.Sprite.Cnds.OnCollision
	];
};
self.C3_JsPropNameTable = [
	{Sprite: 0},
	{Sprite2: 0},
	{Começar: 0},
	{Sprite3: 0},
	{Sólido: 0},
	{TerraComGrama: 0},
	{Sprite4: 0},
	{céu: 0},
	{Funfo: 0},
	{Tutorial: 0},
	{Plataforma: 0},
	{Sprite5: 0},
	{Teclado: 0},
	{Texto: 0},
	{Texto2: 0},
	{Sprite6: 0},
	{Seta: 0},
	{tecla: 0},
	{voltar: 0},
	{voltarini: 0},
	{Sprite8: 0},
	{Senóide: 0},
	{blocoqueempurra: 0},
	{Sprite9: 0},
	{Sprite10: 0},
	{Sprite12: 0},
	{Sprite11: 0},
	{tente: 0}
];

self.InstanceType = {
	Sprite: class extends self.ISpriteInstance {},
	Sprite2: class extends self.ISpriteInstance {},
	Começar: class extends self.IButtonInstance {},
	Sprite3: class extends self.ISpriteInstance {},
	TerraComGrama: class extends self.ISpriteInstance {},
	Sprite4: class extends self.ISpriteInstance {},
	céu: class extends self.ISpriteInstance {},
	Funfo: class extends self.ISpriteInstance {},
	Tutorial: class extends self.IButtonInstance {},
	Sprite5: class extends self.ISpriteInstance {},
	Teclado: class extends self.IInstance {},
	Texto: class extends self.ITextInstance {},
	Texto2: class extends self.ITextInstance {},
	Sprite6: class extends self.ISpriteInstance {},
	Seta: class extends self.ISpriteInstance {},
	tecla: class extends self.ISpriteInstance {},
	voltar: class extends self.ISpriteInstance {},
	voltarini: class extends self.IButtonInstance {},
	Sprite8: class extends self.ISpriteInstance {},
	blocoqueempurra: class extends self.ISpriteInstance {},
	Sprite9: class extends self.ISpriteInstance {},
	Sprite10: class extends self.ISpriteInstance {},
	Sprite12: class extends self.ISpriteInstance {},
	Sprite11: class extends self.ISpriteInstance {},
	tente: class extends self.IButtonInstance {}
}