const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Plugins.Mouse,
		C3.Plugins.Button,
		C3.Plugins.Text,
		C3.Behaviors.EightDir,
		C3.Behaviors.solid,
		C3.Plugins.Camera3D,
		C3.Behaviors.Sin,
		C3.Plugins.SVGPicture,
		C3.Plugins.Mouse.Cnds.OnObjectClicked,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.Sprite.Cnds.OnCollision
	];
};
self.C3_JsPropNameTable = [
	{Sprite: 0},
	{Mouse: 0},
	{pngtreeabstractbackgroundgamingfuturisticbanneronlineimage_: 0},
	{Botão: 0},
	{"1bolinha": 0},
	{Texto: 0},
	{"2Bolinha": 0},
	{Texto2: 0},
	{Sprite2: 0},
	{Texto3: 0},
	{Texto4: 0},
	{Texto5: 0},
	{Sprite3: 0},
	{Sprite4: 0},
	{Texto6: 0},
	{Sprite5: 0},
	{Sprite6: 0},
	{"8Direções": 0},
	{Sprite7: 0},
	{Sprite8: 0},
	{Sprite9: 0},
	{Sprite10: 0},
	{Sprite11: 0},
	{Sprite12: 0},
	{Sprite13: 0},
	{Sólido: 0},
	{Sprite14: 0},
	{Sprite15: 0},
	{Sprite16: 0},
	{Sprite17: 0},
	{Sprite18: 0},
	{Câmera3D: 0},
	{Sprite19: 0},
	{Senóide: 0},
	{Sprite20: 0},
	{Sprite21: 0},
	{Sprite22: 0},
	{pngtreeabstractbackgroundgamingfuturisticbanneronlineimage_2: 0},
	{pngtreeabstractbackgroundgamingfuturisticbanneronlineimage_3: 0},
	{Sprite23: 0},
	{Texto7: 0},
	{Texto8: 0},
	{removebgpreview: 0},
	{Sprite24: 0},
	{Texto9: 0},
	{pngtreeabstractbackgroundgamingfuturisticbanneronlineimage_4: 0},
	{Sprite25: 0},
	{ImagemSVG: 0},
	{Texto10: 0},
	{Texto11: 0},
	{ImagemSVG2: 0},
	{Sprite32: 0},
	{Sprite27: 0}
];

self.InstanceType = {
	Sprite: class extends self.ISpriteInstance {},
	Mouse: class extends self.IInstance {},
	pngtreeabstractbackgroundgamingfuturisticbanneronlineimage_: class extends self.ISpriteInstance {},
	Botão: class extends self.IButtonInstance {},
	_1bolinha: class extends self.ISpriteInstance {},
	Texto: class extends self.ITextInstance {},
	_2Bolinha: class extends self.ISpriteInstance {},
	Texto2: class extends self.ITextInstance {},
	Sprite2: class extends self.ISpriteInstance {},
	Texto3: class extends self.ITextInstance {},
	Texto4: class extends self.ITextInstance {},
	Texto5: class extends self.ITextInstance {},
	Sprite3: class extends self.ISpriteInstance {},
	Sprite4: class extends self.ISpriteInstance {},
	Texto6: class extends self.ITextInstance {},
	Sprite5: class extends self.ISpriteInstance {},
	Sprite6: class extends self.ISpriteInstance {},
	Sprite7: class extends self.ISpriteInstance {},
	Sprite8: class extends self.ISpriteInstance {},
	Sprite9: class extends self.ISpriteInstance {},
	Sprite10: class extends self.ISpriteInstance {},
	Sprite11: class extends self.ISpriteInstance {},
	Sprite12: class extends self.ISpriteInstance {},
	Sprite13: class extends self.ISpriteInstance {},
	Sprite14: class extends self.ISpriteInstance {},
	Sprite15: class extends self.ISpriteInstance {},
	Sprite16: class extends self.ISpriteInstance {},
	Sprite17: class extends self.ISpriteInstance {},
	Sprite18: class extends self.ISpriteInstance {},
	Câmera3D: class extends self.IInstance {},
	Sprite19: class extends self.ISpriteInstance {},
	Sprite20: class extends self.ISpriteInstance {},
	Sprite21: class extends self.ISpriteInstance {},
	Sprite22: class extends self.ISpriteInstance {},
	pngtreeabstractbackgroundgamingfuturisticbanneronlineimage_2: class extends self.ISpriteInstance {},
	pngtreeabstractbackgroundgamingfuturisticbanneronlineimage_3: class extends self.ISpriteInstance {},
	Sprite23: class extends self.ISpriteInstance {},
	Texto7: class extends self.ITextInstance {},
	Texto8: class extends self.ITextInstance {},
	removebgpreview: class extends self.ISpriteInstance {},
	Sprite24: class extends self.ISpriteInstance {},
	Texto9: class extends self.ITextInstance {},
	pngtreeabstractbackgroundgamingfuturisticbanneronlineimage_4: class extends self.ISpriteInstance {},
	Sprite25: class extends self.ISpriteInstance {},
	ImagemSVG: class extends self.ISVGPictureInstance {},
	Texto10: class extends self.ITextInstance {},
	Texto11: class extends self.ITextInstance {},
	ImagemSVG2: class extends self.ISVGPictureInstance {},
	Sprite32: class extends self.ISpriteInstance {},
	Sprite27: class extends self.ISpriteInstance {}
}