const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Behaviors.TileMovement,
		C3.Plugins.Text,
		C3.Behaviors.solid,
		C3.Plugins.Mouse,
		C3.Plugins.Button,
		C3.Behaviors.EightDir,
		C3.Behaviors.Sin,
		C3.Behaviors.Platform,
		C3.Behaviors.scrollto,
		C3.Behaviors.Turret,
		C3.Plugins.Spritefont2,
		C3.Behaviors.Bullet,
		C3.Plugins.Mouse.Cnds.OnObjectClicked,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Plugins.System.Cnds.Every,
		C3.Plugins.Sprite.Acts.Spawn,
		C3.Plugins.Sprite.Acts.Destroy
	];
};
self.C3_JsPropNameTable = [
	{MovimentoEmGrid: 0},
	{Sprite: 0},
	{Sprite2: 0},
	{Sólido: 0},
	{inicio: 0},
	{comoJogar: 0},
	{Mouse: 0},
	{Sprite3: 0},
	{Sprite4: 0},
	{Texto4: 0},
	{Sprite5: 0},
	{Texto5: 0},
	{Button: 0},
	{Sprite6: 0},
	{Text: 0},
	{Text2: 0},
	{voltarinicio: 0},
	{"8Direction": 0},
	{Sprite7: 0},
	{Sprite8: 0},
	{Solid: 0},
	{Sprite9: 0},
	{Sine: 0},
	{Sprite10: 0},
	{Plataforma: 0},
	{CentrarEm: 0},
	{dino: 0},
	{Sprite12: 0},
	{chamasGamerOver: 0},
	{Canhão: 0},
	{Sprite13: 0},
	{Sprite11: 0},
	{Sprite14: 0},
	{Sprite15: 0},
	{FonteDeSprites: 0},
	{Projétil: 0},
	{Sprite16: 0},
	{Sprite17: 0},
	{Sprite18: 0},
	{tesouro: 0},
	{Sprite20: 0},
	{fogoAlto: 0},
	{Sprite19: 0},
	{Sprite21: 0},
	{Sprite22: 0},
	{Texto: 0},
	{textoParabens: 0},
	{REINICIAR: 0},
	{Senóide: 0},
	{Sprite23: 0},
	{Sprite24: 0},
	{REINICIAAR: 0},
	{Sprite25: 0},
	{Sprite26: 0},
	{Sprite27: 0},
	{Sprite28: 0},
	{Sprite29: 0},
	{vulcão: 0},
	{Sprite30: 0},
	{Sprite31: 0},
	{Sprite32: 0},
	{Sprite33: 0},
	{Sprite34: 0},
	{Sprite35: 0},
	{Sprite36: 0},
	{Texto2: 0},
	{Sprite37: 0},
	{Texto3: 0},
	{Sprite38: 0},
	{Texto6: 0},
	{Texto7: 0}
];

self.InstanceType = {
	Sprite: class extends self.ISpriteInstance {},
	Sprite2: class extends self.ISpriteInstance {},
	inicio: class extends self.ITextInstance {},
	comoJogar: class extends self.ITextInstance {},
	Mouse: class extends self.IInstance {},
	Sprite3: class extends self.ISpriteInstance {},
	Sprite4: class extends self.ISpriteInstance {},
	Texto4: class extends self.ITextInstance {},
	Sprite5: class extends self.ISpriteInstance {},
	Texto5: class extends self.ITextInstance {},
	Button: class extends self.IButtonInstance {},
	Sprite6: class extends self.ISpriteInstance {},
	Text: class extends self.ITextInstance {},
	Text2: class extends self.ITextInstance {},
	voltarinicio: class extends self.ITextInstance {},
	Sprite7: class extends self.ISpriteInstance {},
	Sprite8: class extends self.ISpriteInstance {},
	Sprite9: class extends self.ISpriteInstance {},
	Sprite10: class extends self.ISpriteInstance {},
	dino: class extends self.ISpriteInstance {},
	Sprite12: class extends self.ISpriteInstance {},
	chamasGamerOver: class extends self.ISpriteInstance {},
	Sprite13: class extends self.ISpriteInstance {},
	Sprite11: class extends self.ISpriteInstance {},
	Sprite14: class extends self.ISpriteInstance {},
	Sprite15: class extends self.ISpriteInstance {},
	FonteDeSprites: class extends self.ISpriteFontInstance {},
	Sprite16: class extends self.ISpriteInstance {},
	Sprite17: class extends self.ISpriteInstance {},
	Sprite18: class extends self.ISpriteInstance {},
	tesouro: class extends self.ISpriteInstance {},
	Sprite20: class extends self.ISpriteInstance {},
	fogoAlto: class extends self.ISpriteInstance {},
	Sprite19: class extends self.ISpriteInstance {},
	Sprite21: class extends self.ISpriteInstance {},
	Sprite22: class extends self.ISpriteInstance {},
	Texto: class extends self.ITextInstance {},
	textoParabens: class extends self.ITextInstance {},
	REINICIAR: class extends self.ITextInstance {},
	Sprite23: class extends self.ISpriteInstance {},
	Sprite24: class extends self.ISpriteInstance {},
	REINICIAAR: class extends self.ITextInstance {},
	Sprite25: class extends self.ISpriteInstance {},
	Sprite26: class extends self.ISpriteInstance {},
	Sprite27: class extends self.ISpriteInstance {},
	Sprite28: class extends self.ISpriteInstance {},
	Sprite29: class extends self.ISpriteInstance {},
	vulcão: class extends self.ISpriteInstance {},
	Sprite30: class extends self.ISpriteInstance {},
	Sprite31: class extends self.ISpriteInstance {},
	Sprite32: class extends self.ISpriteInstance {},
	Sprite33: class extends self.ISpriteInstance {},
	Sprite34: class extends self.ISpriteInstance {},
	Sprite35: class extends self.ISpriteInstance {},
	Sprite36: class extends self.ISpriteInstance {},
	Texto2: class extends self.ITextInstance {},
	Sprite37: class extends self.ISpriteInstance {},
	Texto3: class extends self.ITextInstance {},
	Sprite38: class extends self.ISpriteInstance {},
	Texto6: class extends self.ITextInstance {},
	Texto7: class extends self.ITextInstance {}
}