const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Plugins.Text,
		C3.Plugins.Mouse,
		C3.Behaviors.Platform,
		C3.Behaviors.scrollto,
		C3.Behaviors.solid,
		C3.Plugins.Button,
		C3.Plugins.Mouse.Cnds.OnObjectClicked,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.Sprite.Cnds.OnCollision
	];
};
self.C3_JsPropNameTable = [
	{Sprite: 0},
	{Sprite2: 0},
	{Sprite3: 0},
	{Sprite4: 0},
	{texto: 0},
	{Sprite5: 0},
	{Sprite6: 0},
	{começar: 0},
	{Sprite7: 0},
	{tutorial: 0},
	{Sprite8: 0},
	{Sprite9: 0},
	{Texto4: 0},
	{Sprite10: 0},
	{voltar: 0},
	{Mouse: 0},
	{Sprite11: 0},
	{lua: 0},
	{Plataforma: 0},
	{CentrarEm: 0},
	{Sprite13: 0},
	{Sprite14: 0},
	{Sólido: 0},
	{chao: 0},
	{Sprite16: 0},
	{Sprite12: 0},
	{Sprite17: 0},
	{Texto2: 0},
	{Sprite18: 0},
	{MENU: 0},
	{Sprite19: 0},
	{Texto3: 0},
	{Sprite21: 0},
	{Sprite20: 0},
	{parede: 0},
	{Sprite15: 0},
	{TENTARNOVAMENTE: 0},
	{Sprite22: 0},
	{MENU2: 0},
	{Texto5: 0},
	{Sprite23: 0},
	{Texto6: 0},
	{Espaço: 0},
	{Texto7: 0}
];

self.InstanceType = {
	Sprite: class extends self.ISpriteInstance {},
	Sprite2: class extends self.ISpriteInstance {},
	Sprite3: class extends self.ISpriteInstance {},
	Sprite4: class extends self.ISpriteInstance {},
	texto: class extends self.ITextInstance {},
	Sprite5: class extends self.ISpriteInstance {},
	Sprite6: class extends self.ISpriteInstance {},
	começar: class extends self.ITextInstance {},
	Sprite7: class extends self.ISpriteInstance {},
	tutorial: class extends self.ITextInstance {},
	Sprite8: class extends self.ISpriteInstance {},
	Sprite9: class extends self.ISpriteInstance {},
	Texto4: class extends self.ITextInstance {},
	Sprite10: class extends self.ISpriteInstance {},
	voltar: class extends self.ITextInstance {},
	Mouse: class extends self.IInstance {},
	Sprite11: class extends self.ISpriteInstance {},
	lua: class extends self.ISpriteInstance {},
	Sprite13: class extends self.ISpriteInstance {},
	Sprite14: class extends self.ISpriteInstance {},
	chao: class extends self.ISpriteInstance {},
	Sprite16: class extends self.ISpriteInstance {},
	Sprite12: class extends self.ISpriteInstance {},
	Sprite17: class extends self.ISpriteInstance {},
	Texto2: class extends self.ITextInstance {},
	Sprite18: class extends self.ISpriteInstance {},
	MENU: class extends self.ITextInstance {},
	Sprite19: class extends self.ISpriteInstance {},
	Texto3: class extends self.ITextInstance {},
	Sprite21: class extends self.ISpriteInstance {},
	Sprite20: class extends self.ISpriteInstance {},
	parede: class extends self.ISpriteInstance {},
	Sprite15: class extends self.ISpriteInstance {},
	TENTARNOVAMENTE: class extends self.ITextInstance {},
	Sprite22: class extends self.ISpriteInstance {},
	MENU2: class extends self.ITextInstance {},
	Texto5: class extends self.ITextInstance {},
	Sprite23: class extends self.ISpriteInstance {},
	Texto6: class extends self.ITextInstance {},
	Espaço: class extends self.IButtonInstance {},
	Texto7: class extends self.ITextInstance {}
}