const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Plugins.Text,
		C3.Behaviors.scrollto,
		C3.Behaviors.EightDir,
		C3.Behaviors.Sin,
		C3.Plugins.Button,
		C3.Behaviors.solid,
		C3.Plugins.Camera3D,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.Button.Cnds.OnClicked
	];
};
self.C3_JsPropNameTable = [
	{Sprite: 0},
	{Sprite2: 0},
	{Sprite3: 0},
	{Sprite4: 0},
	{Texto: 0},
	{Texto2: 0},
	{Texto3: 0},
	{Sprite5: 0},
	{Sprite6: 0},
	{Sprite7: 0},
	{Sprite8: 0},
	{Texto4: 0},
	{Sprite9: 0},
	{Texto5: 0},
	{Sprite10: 0},
	{CentrarEm: 0},
	{"8Direções": 0},
	{junin: 0},
	{Texto6: 0},
	{Sprite12: 0},
	{Texto7: 0},
	{Sprite13: 0},
	{Sprite14: 0},
	{Sprite15: 0},
	{Sprite16: 0},
	{Sprite17: 0},
	{Senóide: 0},
	{Sprite18: 0},
	{an: 0},
	{ju: 0},
	{aa: 0},
	{li: 0},
	{Botão: 0},
	{Botão2: 0},
	{Sólido: 0},
	{Sprite11: 0},
	{Sprite19: 0},
	{Sprite20: 0},
	{Sprite21: 0},
	{Sprite22: 0},
	{Sprite23: 0},
	{Sprite24: 0},
	{Sprite25: 0},
	{Sprite26: 0},
	{Sprite27: 0},
	{Sprite28: 0},
	{Sprite29: 0},
	{Sprite30: 0},
	{Botão3: 0},
	{Texto8: 0},
	{Botão4: 0},
	{Botão5: 0},
	{Câmera3D: 0},
	{Sprite31: 0}
];

self.InstanceType = {
	Sprite: class extends self.ISpriteInstance {},
	Sprite2: class extends self.ISpriteInstance {},
	Sprite3: class extends self.ISpriteInstance {},
	Sprite4: class extends self.ISpriteInstance {},
	Texto: class extends self.ITextInstance {},
	Texto2: class extends self.ITextInstance {},
	Texto3: class extends self.ITextInstance {},
	Sprite5: class extends self.ISpriteInstance {},
	Sprite6: class extends self.ISpriteInstance {},
	Sprite7: class extends self.ISpriteInstance {},
	Sprite8: class extends self.ISpriteInstance {},
	Texto4: class extends self.ITextInstance {},
	Sprite9: class extends self.ISpriteInstance {},
	Texto5: class extends self.ITextInstance {},
	Sprite10: class extends self.ISpriteInstance {},
	junin: class extends self.ISpriteInstance {},
	Texto6: class extends self.ITextInstance {},
	Sprite12: class extends self.ISpriteInstance {},
	Texto7: class extends self.ITextInstance {},
	Sprite13: class extends self.ISpriteInstance {},
	Sprite14: class extends self.ISpriteInstance {},
	Sprite15: class extends self.ISpriteInstance {},
	Sprite16: class extends self.ISpriteInstance {},
	Sprite17: class extends self.ISpriteInstance {},
	Sprite18: class extends self.ISpriteInstance {},
	an: class extends self.ISpriteInstance {},
	ju: class extends self.ISpriteInstance {},
	aa: class extends self.ISpriteInstance {},
	li: class extends self.ISpriteInstance {},
	Botão: class extends self.IButtonInstance {},
	Botão2: class extends self.IButtonInstance {},
	Sprite11: class extends self.ISpriteInstance {},
	Sprite19: class extends self.ISpriteInstance {},
	Sprite20: class extends self.ISpriteInstance {},
	Sprite21: class extends self.ISpriteInstance {},
	Sprite22: class extends self.ISpriteInstance {},
	Sprite23: class extends self.ISpriteInstance {},
	Sprite24: class extends self.ISpriteInstance {},
	Sprite25: class extends self.ISpriteInstance {},
	Sprite26: class extends self.ISpriteInstance {},
	Sprite27: class extends self.ISpriteInstance {},
	Sprite28: class extends self.ISpriteInstance {},
	Sprite29: class extends self.ISpriteInstance {},
	Sprite30: class extends self.ISpriteInstance {},
	Botão3: class extends self.IButtonInstance {},
	Texto8: class extends self.ITextInstance {},
	Botão4: class extends self.IButtonInstance {},
	Botão5: class extends self.IButtonInstance {},
	Câmera3D: class extends self.IInstance {},
	Sprite31: class extends self.ISpriteInstance {}
}