const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Plugins.Touch,
		C3.Behaviors.solid,
		C3.Behaviors.Bullet,
		C3.Behaviors.Platform,
		C3.Behaviors.bound,
		C3.Plugins.Particles,
		C3.Plugins.Text,
		C3.Plugins.Audio,
		C3.Plugins.Button,
		C3.Plugins.Camera3D,
		C3.Plugins.Mouse,
		C3.Plugins.Touch.Cnds.OnTouchObject,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.Touch.Cnds.IsTouchingObject,
		C3.Behaviors.Platform.Acts.SimulateControl,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.Text.Acts.SetText,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.Audio.Acts.StopAll,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.System.Cnds.Every,
		C3.Plugins.System.Exps.random,
		C3.Plugins.System.Acts.CreateObject,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.Sprite.Acts.Spawn,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.System.Acts.Wait
	];
};
self.C3_JsPropNameTable = [
	{BOTÃOTUTO: 0},
	{play: 0},
	{Toque: 0},
	{Sprite2: 0},
	{Sólido: 0},
	{chão: 0},
	{Projétil: 0},
	{bomba: 0},
	{moedas: 0},
	{Plataforma: 0},
	{RestritoAoLayout: 0},
	{Sprite3: 0},
	{direito: 0},
	{esquerdo: 0},
	{Partículasmoeda: 0},
	{Partículasmoeda2: 0},
	{Sprite4: 0},
	{Texto: 0},
	{Áudio: 0},
	{Sprite5: 0},
	{Botão: 0},
	{Sprite6: 0},
	{Botão2: 0},
	{Sprite: 0},
	{Sprite7: 0},
	{Sprite8: 0},
	{Câmera3D: 0},
	{Sprite9: 0},
	{Mouse: 0},
	{Sprite10: 0},
	{Botão3: 0},
	{Sprite11: 0},
	{Sprite12: 0},
	{Sprite13: 0},
	{Sprite14: 0},
	{pontos: 0}
];

self.InstanceType = {
	BOTÃOTUTO: class extends self.ISpriteInstance {},
	play: class extends self.ISpriteInstance {},
	Toque: class extends self.IInstance {},
	Sprite2: class extends self.ISpriteInstance {},
	chão: class extends self.ISpriteInstance {},
	bomba: class extends self.ISpriteInstance {},
	moedas: class extends self.ISpriteInstance {},
	Sprite3: class extends self.ISpriteInstance {},
	direito: class extends self.ISpriteInstance {},
	esquerdo: class extends self.ISpriteInstance {},
	Partículasmoeda: class extends self.IParticlesInstance {},
	Partículasmoeda2: class extends self.IParticlesInstance {},
	Sprite4: class extends self.ISpriteInstance {},
	Texto: class extends self.ITextInstance {},
	Áudio: class extends self.IInstance {},
	Sprite5: class extends self.ISpriteInstance {},
	Botão: class extends self.IButtonInstance {},
	Sprite6: class extends self.ISpriteInstance {},
	Botão2: class extends self.IButtonInstance {},
	Sprite: class extends self.ISpriteInstance {},
	Sprite7: class extends self.ISpriteInstance {},
	Sprite8: class extends self.ISpriteInstance {},
	Câmera3D: class extends self.IInstance {},
	Sprite9: class extends self.ISpriteInstance {},
	Mouse: class extends self.IInstance {},
	Sprite10: class extends self.ISpriteInstance {},
	Botão3: class extends self.IButtonInstance {},
	Sprite11: class extends self.ISpriteInstance {},
	Sprite12: class extends self.ISpriteInstance {},
	Sprite13: class extends self.ISpriteInstance {},
	Sprite14: class extends self.ISpriteInstance {}
}