const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Button,
		C3.Plugins.Text,
		C3.Plugins.Sprite,
		C3.Plugins.Button.Cnds.OnClicked,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.Text.Acts.SetText,
		C3.Plugins.System.Acts.GoToLayout
	];
};
self.C3_JsPropNameTable = [
	{Botão: 0},
	{Texto: 0},
	{download: 0},
	{download2: 0},
	{images: 0},
	{channels4_profile: 0},
	{Texto2: 0},
	{pngtransparentarrowcomputersoftwarecomputericonsvideogamedownarrowpurplegameangleremovebgpreview: 0},
	{iniciar: 0},
	{tutorial: 0},
	{renderizacao3ddeperguntasdefundo_: 0},
	{Texto3: 0},
	{Texto4: 0},
	{removebgpreview: 0},
	{voltarParaOInicio: 0},
	{tecido_tricoline_liso_lilas_837_1_95d8f930ca50b2de043d8498c6537f5f: 0},
	{Texto5: 0},
	{download3: 0},
	{YuriGagarin: 0},
	{ThomasEdison: 0},
	{MartinCooper: 0},
	{TALESDEMILETO: 0},
	{a0e77c2f: 0},
	{image: 0},
	{Texto6: 0},
	{demogorgo: 0},
	{godzilla: 0},
	{DevoradorDeMentes: 0},
	{download4: 0},
	{image2: 0},
	{Texto7: 0},
	{OceanoAtlântico: 0},
	{OceanoPacífico: 0},
	{OceanoÍndico: 0},
	{OceanoÁrtico: 0},
	{fundodetexturadetelaazul_: 0},
	{Sprite: 0},
	{iconedesetadecurvagratisvetorremovebgpreview: 0},
	{Texto8: 0},
	{CLIQUEPARAJOGARDENOVO: 0},
	{iconedesetadecurvagratisvetorremovebgpreview2: 0},
	{fundodetexturadetelaazul_2: 0},
	{VCPERDEU: 0},
	{CLIQUEPARATENTARNOVAMENTE: 0},
	{iconedesetadecurvagratisvetorremovebgpreview3: 0},
	{ummeninocompodereselementais: 0},
	{images2: 0},
	{imagesremovebgpreview: 0},
	{cachorinho: 0}
];

self.InstanceType = {
	Botão: class extends self.IButtonInstance {},
	Texto: class extends self.ITextInstance {},
	download: class extends self.ISpriteInstance {},
	download2: class extends self.ISpriteInstance {},
	images: class extends self.ISpriteInstance {},
	channels4_profile: class extends self.ISpriteInstance {},
	Texto2: class extends self.ITextInstance {},
	pngtransparentarrowcomputersoftwarecomputericonsvideogamedownarrowpurplegameangleremovebgpreview: class extends self.ISpriteInstance {},
	iniciar: class extends self.IButtonInstance {},
	tutorial: class extends self.IButtonInstance {},
	renderizacao3ddeperguntasdefundo_: class extends self.ISpriteInstance {},
	Texto3: class extends self.ITextInstance {},
	Texto4: class extends self.ITextInstance {},
	removebgpreview: class extends self.ISpriteInstance {},
	voltarParaOInicio: class extends self.IButtonInstance {},
	tecido_tricoline_liso_lilas_837_1_95d8f930ca50b2de043d8498c6537f5f: class extends self.ISpriteInstance {},
	Texto5: class extends self.ITextInstance {},
	download3: class extends self.ISpriteInstance {},
	YuriGagarin: class extends self.IButtonInstance {},
	ThomasEdison: class extends self.IButtonInstance {},
	MartinCooper: class extends self.IButtonInstance {},
	TALESDEMILETO: class extends self.IButtonInstance {},
	a0e77c2f: class extends self.ISpriteInstance {},
	image: class extends self.ISpriteInstance {},
	Texto6: class extends self.ITextInstance {},
	demogorgo: class extends self.IButtonInstance {},
	godzilla: class extends self.IButtonInstance {},
	DevoradorDeMentes: class extends self.IButtonInstance {},
	download4: class extends self.ISpriteInstance {},
	image2: class extends self.ISpriteInstance {},
	Texto7: class extends self.ITextInstance {},
	OceanoAtlântico: class extends self.IButtonInstance {},
	OceanoPacífico: class extends self.IButtonInstance {},
	OceanoÍndico: class extends self.IButtonInstance {},
	OceanoÁrtico: class extends self.IButtonInstance {},
	fundodetexturadetelaazul_: class extends self.ISpriteInstance {},
	Sprite: class extends self.ISpriteInstance {},
	iconedesetadecurvagratisvetorremovebgpreview: class extends self.ISpriteInstance {},
	Texto8: class extends self.ITextInstance {},
	CLIQUEPARAJOGARDENOVO: class extends self.IButtonInstance {},
	iconedesetadecurvagratisvetorremovebgpreview2: class extends self.ISpriteInstance {},
	fundodetexturadetelaazul_2: class extends self.ISpriteInstance {},
	VCPERDEU: class extends self.ITextInstance {},
	CLIQUEPARATENTARNOVAMENTE: class extends self.IButtonInstance {},
	iconedesetadecurvagratisvetorremovebgpreview3: class extends self.ISpriteInstance {},
	ummeninocompodereselementais: class extends self.ISpriteInstance {},
	images2: class extends self.ISpriteInstance {},
	imagesremovebgpreview: class extends self.ISpriteInstance {}
}