const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Plugins.Button,
		C3.Behaviors.solid,
		C3.Behaviors.Sin,
		C3.Behaviors.Platform,
		C3.Plugins.Text,
		C3.Behaviors.Turret,
		C3.Plugins.Mouse,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.Button.Cnds.OnClicked
	];
};
self.C3_JsPropNameTable = [
	{Sprite: 0},
	{jogar1: 0},
	{TUTURI: 0},
	{TUTURIAL: 0},
	{Sprite3: 0},
	{imagesremovebgpreview2: 0},
	{Sólido: 0},
	{Senóide: 0},
	{imagesremovebgpreview4: 0},
	{imagesremovebgpreview5: 0},
	{VENCEU: 0},
	{Sprite5: 0},
	{Plataforma: 0},
	{imagesremovebgpreview: 0},
	{downloadremovebgpreview: 0},
	{perdeu: 0},
	{Sprite4: 0},
	{Botão3: 0},
	{TENTE: 0},
	{Texto: 0},
	{Texto2: 0},
	{JOGARNVM: 0},
	{c8b0bcfd825925d40bf50f148c164eremovebgpreview: 0},
	{imagesremovebgpreview3: 0},
	{mushumulanremovebgpreview: 0},
	{Texto3: 0},
	{Texto4: 0},
	{mushumulanremovebgpreview2: 0},
	{Texto5: 0},
	{MENUTUTU: 0},
	{TETI: 0},
	{pngtreeredandblackgradientsimplemaroonbackgroundimage_: 0},
	{Canhão: 0},
	{v4460pxMakeaDisney_sMulanCostumeStep22Version2removebgpreview: 0},
	{Mouse: 0}
];

self.InstanceType = {
	Sprite: class extends self.ISpriteInstance {},
	jogar1: class extends self.IButtonInstance {},
	TUTURI: class extends self.IButtonInstance {},
	TUTURIAL: class extends self.ISpriteInstance {},
	Sprite3: class extends self.ISpriteInstance {},
	imagesremovebgpreview2: class extends self.ISpriteInstance {},
	imagesremovebgpreview4: class extends self.ISpriteInstance {},
	imagesremovebgpreview5: class extends self.ISpriteInstance {},
	VENCEU: class extends self.ISpriteInstance {},
	Sprite5: class extends self.ISpriteInstance {},
	imagesremovebgpreview: class extends self.ISpriteInstance {},
	downloadremovebgpreview: class extends self.ISpriteInstance {},
	perdeu: class extends self.ITextInstance {},
	Sprite4: class extends self.ISpriteInstance {},
	Botão3: class extends self.IButtonInstance {},
	TENTE: class extends self.ITextInstance {},
	Texto: class extends self.ITextInstance {},
	Texto2: class extends self.ITextInstance {},
	JOGARNVM: class extends self.IButtonInstance {},
	c8b0bcfd825925d40bf50f148c164eremovebgpreview: class extends self.ISpriteInstance {},
	imagesremovebgpreview3: class extends self.ISpriteInstance {},
	mushumulanremovebgpreview: class extends self.ISpriteInstance {},
	Texto3: class extends self.ITextInstance {},
	Texto4: class extends self.ITextInstance {},
	mushumulanremovebgpreview2: class extends self.ISpriteInstance {},
	Texto5: class extends self.ITextInstance {},
	MENUTUTU: class extends self.IButtonInstance {},
	TETI: class extends self.ISpriteInstance {},
	pngtreeredandblackgradientsimplemaroonbackgroundimage_: class extends self.ISpriteInstance {},
	v4460pxMakeaDisney_sMulanCostumeStep22Version2removebgpreview: class extends self.ISpriteInstance {},
	Mouse: class extends self.IInstance {}
}