const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Plugins.Text,
		C3.Plugins.Mouse,
		C3.Behaviors.Platform,
		C3.Behaviors.Bullet,
		C3.Plugins.Keyboard,
		C3.Behaviors.solid,
		C3.Plugins.Mouse.Cnds.OnObjectClicked,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.Keyboard.Cnds.OnKey,
		C3.Plugins.Sprite.Acts.Spawn,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Plugins.Sprite.Acts.Destroy
	];
};
self.C3_JsPropNameTable = [
	{Sprite: 0},
	{Sprite2: 0},
	{Sprite3: 0},
	{Texto: 0},
	{botoesbotaocamisariabotaotransparente4furosc144undp1623338394167removebgpreview: 0},
	{pngtransparentgamebuttons3dthreedimensionalorangethumbnailremovebgpreview: 0},
	{Gamehomeiconbuttongameswitchstayhomestaysafe_127975_wh860removebgpreview: 0},
	{Mouse: 0},
	{setupinfinite2dspacegamebackgroundv0xetvk2wxejia: 0},
	{images: 0},
	{Sprite4: 0},
	{Texto2: 0},
	{pngtransparentgamebuttons3dthreedimensionalorangethumbnailremovebgpreview2: 0},
	{Texto3: 0},
	{pngtreegamemariopngimage_6544086removebgpreview: 0},
	{Sprite5: 0},
	{Plataforma: 0},
	{Sprite6: 0},
	{Sprite7: 0},
	{Projétil: 0},
	{Sprite8: 0},
	{Teclado: 0},
	{Sólido: 0},
	{Sprite9: 0},
	{Sprite10: 0},
	{Sprite11: 0},
	{Sprite12: 0},
	{Sprite13: 0},
	{pngclipartcasinogamedrawingcasinowingameangleremovebgpreview: 0},
	{pngtransparentgamebuttons3dthreedimensionalorangethumbnail: 0},
	{pngclipartcasinogamedrawingcasinowingameangle: 0},
	{pngtransparentgamebuttons3dthreedimensionalorangethumbnailremovebgpreview3: 0},
	{Sprite14: 0},
	{Sprite15: 0},
	{Sprite16: 0},
	{pngtransparenthomersimpsonthesimpsonstappedoutsadnessdeathhomerdohtelevisiontextsadnessremovebgpreview: 0},
	{pngtransparentgamebuttons3dthreedimensionalorangethumbnailremovebgpreview4: 0},
	{Texto4: 0},
	{Texto5: 0},
	{Texto6: 0},
	{Texto7: 0}
];

self.InstanceType = {
	Sprite: class extends self.ISpriteInstance {},
	Sprite2: class extends self.ISpriteInstance {},
	Sprite3: class extends self.ISpriteInstance {},
	Texto: class extends self.ITextInstance {},
	botoesbotaocamisariabotaotransparente4furosc144undp1623338394167removebgpreview: class extends self.ISpriteInstance {},
	pngtransparentgamebuttons3dthreedimensionalorangethumbnailremovebgpreview: class extends self.ISpriteInstance {},
	Gamehomeiconbuttongameswitchstayhomestaysafe_127975_wh860removebgpreview: class extends self.ISpriteInstance {},
	Mouse: class extends self.IInstance {},
	setupinfinite2dspacegamebackgroundv0xetvk2wxejia: class extends self.ISpriteInstance {},
	images: class extends self.ISpriteInstance {},
	Sprite4: class extends self.ISpriteInstance {},
	Texto2: class extends self.ITextInstance {},
	pngtransparentgamebuttons3dthreedimensionalorangethumbnailremovebgpreview2: class extends self.ISpriteInstance {},
	Texto3: class extends self.ITextInstance {},
	pngtreegamemariopngimage_6544086removebgpreview: class extends self.ISpriteInstance {},
	Sprite5: class extends self.ISpriteInstance {},
	Sprite6: class extends self.ISpriteInstance {},
	Sprite7: class extends self.ISpriteInstance {},
	Sprite8: class extends self.ISpriteInstance {},
	Teclado: class extends self.IInstance {},
	Sprite9: class extends self.ISpriteInstance {},
	Sprite10: class extends self.ISpriteInstance {},
	Sprite11: class extends self.ISpriteInstance {},
	Sprite12: class extends self.ISpriteInstance {},
	Sprite13: class extends self.ISpriteInstance {},
	pngclipartcasinogamedrawingcasinowingameangleremovebgpreview: class extends self.ISpriteInstance {},
	pngtransparentgamebuttons3dthreedimensionalorangethumbnail: class extends self.ISpriteInstance {},
	pngclipartcasinogamedrawingcasinowingameangle: class extends self.ISpriteInstance {},
	pngtransparentgamebuttons3dthreedimensionalorangethumbnailremovebgpreview3: class extends self.ISpriteInstance {},
	Sprite14: class extends self.ISpriteInstance {},
	Sprite15: class extends self.ISpriteInstance {},
	Sprite16: class extends self.ISpriteInstance {},
	pngtransparenthomersimpsonthesimpsonstappedoutsadnessdeathhomerdohtelevisiontextsadnessremovebgpreview: class extends self.ISpriteInstance {},
	pngtransparentgamebuttons3dthreedimensionalorangethumbnailremovebgpreview4: class extends self.ISpriteInstance {},
	Texto4: class extends self.ITextInstance {},
	Texto5: class extends self.ITextInstance {},
	Texto6: class extends self.ITextInstance {},
	Texto7: class extends self.ITextInstance {}
}