const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Plugins.Text,
		C3.Plugins.TextBox,
		C3.Plugins.Mouse,
		C3.Plugins.TiledBg,
		C3.Behaviors.solid,
		C3.Behaviors.scrollto,
		C3.Behaviors.EightDir,
		C3.Plugins.Keyboard,
		C3.Plugins.Mouse.Cnds.OnObjectClicked,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Plugins.Sprite.Acts.Destroy
	];
};
self.C3_JsPropNameTable = [
	{TelaInicial: 0},
	{Play: 0},
	{Texto: 0},
	{Tutorial: 0},
	{Texto2: 0},
	{Sprite: 0},
	{Texto3: 0},
	{Texto4: 0},
	{Texto5: 0},
	{Voltar: 0},
	{EntradaDeTexto: 0},
	{Texto6: 0},
	{Mouse: 0},
	{Sprite2: 0},
	{Sólido: 0},
	{PlanoDeFundoEmBlocos: 0},
	{CentrarEm: 0},
	{"8Direções": 0},
	{Sprite3: 0},
	{Teclado: 0},
	{Sprite4: 0},
	{Sprite5: 0},
	{Sprite6: 0},
	{Sprite7: 0},
	{Sprite8: 0},
	{Sprite9: 0},
	{Texto7: 0},
	{VoltarParaMenuInicial: 0},
	{EntradaDeTexto2: 0},
	{Texto8: 0},
	{Sprite10: 0},
	{Sprite11: 0},
	{Texto9: 0},
	{VoltarParaInicio: 0},
	{EntradaDeTexto3: 0},
	{Texto10: 0},
	{Sprite12: 0},
	{Sprite13: 0},
	{Texto11: 0}
];

self.InstanceType = {
	TelaInicial: class extends self.ISpriteInstance {},
	Play: class extends self.ISpriteInstance {},
	Texto: class extends self.ITextInstance {},
	Tutorial: class extends self.ISpriteInstance {},
	Texto2: class extends self.ITextInstance {},
	Sprite: class extends self.ISpriteInstance {},
	Texto3: class extends self.ITextInstance {},
	Texto4: class extends self.ITextInstance {},
	Texto5: class extends self.ITextInstance {},
	Voltar: class extends self.ISpriteInstance {},
	EntradaDeTexto: class extends self.ITextInputInstance {},
	Texto6: class extends self.ITextInstance {},
	Mouse: class extends self.IInstance {},
	Sprite2: class extends self.ISpriteInstance {},
	PlanoDeFundoEmBlocos: class extends self.ITiledBackgroundInstance {},
	Sprite3: class extends self.ISpriteInstance {},
	Teclado: class extends self.IInstance {},
	Sprite4: class extends self.ISpriteInstance {},
	Sprite5: class extends self.ISpriteInstance {},
	Sprite6: class extends self.ISpriteInstance {},
	Sprite7: class extends self.ISpriteInstance {},
	Sprite8: class extends self.ISpriteInstance {},
	Sprite9: class extends self.ISpriteInstance {},
	Texto7: class extends self.ITextInstance {},
	VoltarParaMenuInicial: class extends self.ISpriteInstance {},
	EntradaDeTexto2: class extends self.ITextInputInstance {},
	Texto8: class extends self.ITextInstance {},
	Sprite10: class extends self.ISpriteInstance {},
	Sprite11: class extends self.ISpriteInstance {},
	Texto9: class extends self.ITextInstance {},
	VoltarParaInicio: class extends self.ISpriteInstance {},
	EntradaDeTexto3: class extends self.ITextInputInstance {},
	Texto10: class extends self.ITextInstance {},
	Sprite12: class extends self.ISpriteInstance {},
	Sprite13: class extends self.ISpriteInstance {},
	Texto11: class extends self.ITextInstance {}
}