const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Plugins.Text,
		C3.Plugins.Mouse,
		C3.Behaviors.Pin,
		C3.Behaviors.scrollto,
		C3.Behaviors.EightDir,
		C3.Behaviors.solid,
		C3.Behaviors.Sin,
		C3.Plugins.Mouse.Cnds.OnObjectClicked,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.Sprite.Cnds.OnCollision
	];
};
self.C3_JsPropNameTable = [
	{Sprite: 0},
	{Computador: 0},
	{Sprite3: 0},
	{Welcome: 0},
	{Sprite5: 0},
	{Tutorial: 0},
	{StartMenu: 0},
	{ComputadorTutorial: 0},
	{Texto: 0},
	{StartTutorial: 0},
	{VoltarParaOMenu: 0},
	{Mouse: 0},
	{Fixar: 0},
	{Labirinto: 0},
	{CentrarEm: 0},
	{"8Direções": 0},
	{VírusoJoggo: 0},
	{Sólido: 0},
	{Labirinto2: 0},
	{Senóide: 0},
	{Escudo2: 0},
	{Escudo4: 0},
	{Escudo1: 0},
	{Escudo3: 0},
	{Sprite2: 0},
	{Sprite4: 0},
	{Arquivos: 0},
	{Computador2: 0},
	{Sprite6: 0},
	{Texto2: 0},
	{Sprite7: 0},
	{Sprite8: 0},
	{Sprite9: 0},
	{Sprite10: 0},
	{Sprite11: 0},
	{Texto3: 0}
];

self.InstanceType = {
	Sprite: class extends self.ISpriteInstance {},
	Computador: class extends self.ISpriteInstance {},
	Sprite3: class extends self.ISpriteInstance {},
	Welcome: class extends self.ISpriteInstance {},
	Sprite5: class extends self.ISpriteInstance {},
	Tutorial: class extends self.ISpriteInstance {},
	StartMenu: class extends self.ISpriteInstance {},
	ComputadorTutorial: class extends self.ISpriteInstance {},
	Texto: class extends self.ITextInstance {},
	StartTutorial: class extends self.ISpriteInstance {},
	VoltarParaOMenu: class extends self.ISpriteInstance {},
	Mouse: class extends self.IInstance {},
	Labirinto: class extends self.ISpriteInstance {},
	VírusoJoggo: class extends self.ISpriteInstance {},
	Labirinto2: class extends self.ISpriteInstance {},
	Escudo2: class extends self.ISpriteInstance {},
	Escudo4: class extends self.ISpriteInstance {},
	Escudo1: class extends self.ISpriteInstance {},
	Escudo3: class extends self.ISpriteInstance {},
	Sprite2: class extends self.ISpriteInstance {},
	Sprite4: class extends self.ISpriteInstance {},
	Arquivos: class extends self.ISpriteInstance {},
	Computador2: class extends self.ISpriteInstance {},
	Sprite6: class extends self.ISpriteInstance {},
	Texto2: class extends self.ITextInstance {},
	Sprite7: class extends self.ISpriteInstance {},
	Sprite8: class extends self.ISpriteInstance {},
	Sprite9: class extends self.ISpriteInstance {},
	Sprite10: class extends self.ISpriteInstance {},
	Sprite11: class extends self.ISpriteInstance {},
	Texto3: class extends self.ITextInstance {}
}