const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Button,
		C3.Plugins.Text,
		C3.Plugins.Sprite,
		C3.Behaviors.solid,
		C3.Behaviors.Platform,
		C3.Plugins.TiledBg,
		C3.Behaviors.scrollto,
		C3.Plugins.Button.Cnds.OnClicked,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.Sprite.Cnds.OnCollision
	];
};
self.C3_JsPropNameTable = [
	{BotãoT: 0},
	{BotãoC: 0},
	{Texto: 0},
	{Sólido: 0},
	{Sprite: 0},
	{Plataforma: 0},
	{Plataforma2: 0},
	{Plataforma3: 0},
	{Sprite2: 0},
	{Sprite4: 0},
	{Sprite5: 0},
	{Texto2: 0},
	{PlanoDeFundoEmBlocos: 0},
	{PlanoDeFundoEmBlocos2: 0},
	{PlanoDeFundoEmBlocos3: 0},
	{Sprite3: 0},
	{Sprite6: 0},
	{CentrarEm: 0},
	{Sprite7: 0},
	{PlanoDeFundoEmBlocos4: 0},
	{Sprite8: 0},
	{Sprite9: 0},
	{Sprite10: 0},
	{Sprite11: 0},
	{Sprite12: 0},
	{Texto3: 0},
	{Botão: 0},
	{PlanoDeFundoEmBlocos5: 0},
	{Sprite13: 0},
	{Sprite14: 0},
	{Botão2: 0},
	{PlanoDeFundoEmBlocos6: 0},
	{PlanoDeFundoEmBlocos7: 0},
	{Sprite15: 0},
	{Sprite16: 0},
	{Botão3: 0}
];

self.InstanceType = {
	BotãoT: class extends self.IButtonInstance {},
	BotãoC: class extends self.IButtonInstance {},
	Texto: class extends self.ITextInstance {},
	Sprite: class extends self.ISpriteInstance {},
	Sprite2: class extends self.ISpriteInstance {},
	Sprite4: class extends self.ISpriteInstance {},
	Sprite5: class extends self.ISpriteInstance {},
	Texto2: class extends self.ITextInstance {},
	PlanoDeFundoEmBlocos: class extends self.ITiledBackgroundInstance {},
	PlanoDeFundoEmBlocos2: class extends self.ITiledBackgroundInstance {},
	PlanoDeFundoEmBlocos3: class extends self.ITiledBackgroundInstance {},
	Sprite3: class extends self.ISpriteInstance {},
	Sprite6: class extends self.ISpriteInstance {},
	Sprite7: class extends self.ISpriteInstance {},
	PlanoDeFundoEmBlocos4: class extends self.ITiledBackgroundInstance {},
	Sprite8: class extends self.ISpriteInstance {},
	Sprite9: class extends self.ISpriteInstance {},
	Sprite10: class extends self.ISpriteInstance {},
	Sprite11: class extends self.ISpriteInstance {},
	Sprite12: class extends self.ISpriteInstance {},
	Texto3: class extends self.ITextInstance {},
	Botão: class extends self.IButtonInstance {},
	PlanoDeFundoEmBlocos5: class extends self.ITiledBackgroundInstance {},
	Sprite13: class extends self.ISpriteInstance {},
	Sprite14: class extends self.ISpriteInstance {},
	Botão2: class extends self.IButtonInstance {},
	PlanoDeFundoEmBlocos6: class extends self.ITiledBackgroundInstance {},
	PlanoDeFundoEmBlocos7: class extends self.ITiledBackgroundInstance {},
	Sprite15: class extends self.ISpriteInstance {},
	Sprite16: class extends self.ISpriteInstance {},
	Botão3: class extends self.IButtonInstance {}
}