const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Behaviors.Platform,
		C3.Plugins.Text,
		C3.Plugins.Mouse,
		C3.Behaviors.solid,
		C3.Behaviors.Bullet,
		C3.Plugins.Keyboard,
		C3.Plugins.Mouse.Cnds.OnObjectClicked,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.System.Cnds.Every,
		C3.Plugins.Sprite.Acts.Spawn,
		C3.Behaviors.Bullet.Acts.SetAngleOfMotion,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Plugins.Keyboard.Cnds.OnKey,
		C3.Plugins.Sprite.Acts.Destroy
	];
};
self.C3_JsPropNameTable = [
	{Sprite: 0},
	{Sprite2: 0},
	{BotãoJogar: 0},
	{Sprite4: 0},
	{Sprite5: 0},
	{Sprite6: 0},
	{Sprite7: 0},
	{Sprite8: 0},
	{Sprite9: 0},
	{Sprite10: 0},
	{Sprite11: 0},
	{Plataforma: 0},
	{Sprite12: 0},
	{Sprite13: 0},
	{Texto: 0},
	{Texto2: 0},
	{Sprite14: 0},
	{Texto3: 0},
	{Texto4: 0},
	{Texto5: 0},
	{Texto6: 0},
	{Mouse: 0},
	{Sólido: 0},
	{Sprite15: 0},
	{BotãoTutorial: 0},
	{BotãoTutorial2: 0},
	{BotãoJogar2: 0},
	{BotãoVoltarporMenu: 0},
	{BotãoVoltarpromenu2: 0},
	{BotãoJogardenovo: 0},
	{Projétil: 0},
	{Boladefogoescura: 0},
	{BolaDeFogoAzul: 0},
	{Teclado: 0},
	{Texto7: 0},
	{Sprite3: 0}
];

self.InstanceType = {
	Sprite: class extends self.ISpriteInstance {},
	Sprite2: class extends self.ISpriteInstance {},
	BotãoJogar: class extends self.ISpriteInstance {},
	Sprite4: class extends self.ISpriteInstance {},
	Sprite5: class extends self.ISpriteInstance {},
	Sprite6: class extends self.ISpriteInstance {},
	Sprite7: class extends self.ISpriteInstance {},
	Sprite8: class extends self.ISpriteInstance {},
	Sprite9: class extends self.ISpriteInstance {},
	Sprite10: class extends self.ISpriteInstance {},
	Sprite11: class extends self.ISpriteInstance {},
	Sprite12: class extends self.ISpriteInstance {},
	Sprite13: class extends self.ISpriteInstance {},
	Texto: class extends self.ITextInstance {},
	Texto2: class extends self.ITextInstance {},
	Sprite14: class extends self.ISpriteInstance {},
	Texto3: class extends self.ITextInstance {},
	Texto4: class extends self.ITextInstance {},
	Texto5: class extends self.ITextInstance {},
	Texto6: class extends self.ITextInstance {},
	Mouse: class extends self.IInstance {},
	Sprite15: class extends self.ISpriteInstance {},
	BotãoTutorial: class extends self.ISpriteInstance {},
	BotãoTutorial2: class extends self.ISpriteInstance {},
	BotãoJogar2: class extends self.ISpriteInstance {},
	BotãoVoltarporMenu: class extends self.ISpriteInstance {},
	BotãoVoltarpromenu2: class extends self.ISpriteInstance {},
	BotãoJogardenovo: class extends self.ISpriteInstance {},
	Boladefogoescura: class extends self.ISpriteInstance {},
	BolaDeFogoAzul: class extends self.ISpriteInstance {},
	Teclado: class extends self.IInstance {},
	Texto7: class extends self.ITextInstance {},
	Sprite3: class extends self.ISpriteInstance {}
}