const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Mouse,
		C3.Plugins.Sprite,
		C3.Plugins.Text,
		C3.Plugins.Button,
		C3.Behaviors.scrollto,
		C3.Behaviors.EightDir,
		C3.Behaviors.solid,
		C3.Plugins.Keyboard,
		C3.Behaviors.Bullet,
		C3.Behaviors.Rotate,
		C3.Behaviors.Sin,
		C3.Plugins.Button.Cnds.OnClicked,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.Mouse.Cnds.OnObjectClicked,
		C3.Plugins.Keyboard.Cnds.OnKey,
		C3.Plugins.Sprite.Acts.Spawn,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Plugins.System.Acts.RestartLayout,
		C3.Plugins.Sprite.Acts.SetPos,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Behaviors.Bullet.Acts.Bounce
	];
};
self.C3_JsPropNameTable = [
	{Mouse: 0},
	{Sprite: 0},
	{Texto: 0},
	{PlayJg: 0},
	{tuturial: 0},
	{Sprite2: 0},
	{Sprite3: 0},
	{Sprite4: 0},
	{Texto2: 0},
	{Jogar: 0},
	{Sprite5: 0},
	{Texto3: 0},
	{Texto4: 0},
	{Texto5: 0},
	{ERRADADA1: 0},
	{CERTADA1: 0},
	{Sprite6: 0},
	{Sprite7: 0},
	{Sprite8: 0},
	{Sprite9: 0},
	{Texto6: 0},
	{Texto7: 0},
	{VOLTAR: 0},
	{Sprite10: 0},
	{Texto8: 0},
	{Texto9: 0},
	{NIKE: 0},
	{Sprite11: 0},
	{Texto10: 0},
	{ERRADODA2: 0},
	{CORRETADA2: 0},
	{Sprite12: 0},
	{Texto11: 0},
	{Sprite13: 0},
	{Texto12: 0},
	{TRANSIÇÃO: 0},
	{Botão2: 0},
	{Sprite14: 0},
	{Sprite15: 0},
	{Texto13: 0},
	{Texto14: 0},
	{Texto15: 0},
	{FLOR: 0},
	{Sprite16: 0},
	{Texto16: 0},
	{Sprite17: 0},
	{bolinha: 0},
	{Sprite18: 0},
	{CentrarEm: 0},
	{"8Direções": 0},
	{ney: 0},
	{Sólido: 0},
	{Sprite20: 0},
	{Teclado: 0},
	{Projétil: 0},
	{Sprite19: 0},
	{Girar: 0},
	{gira: 0},
	{Senóide: 0},
	{Sprite21: 0},
	{Sprite22: 0},
	{Sprite23: 0},
	{Sprite24: 0},
	{Texto17: 0},
	{Texto18: 0},
	{laele: 0}
];

self.InstanceType = {
	Mouse: class extends self.IInstance {},
	Sprite: class extends self.ISpriteInstance {},
	Texto: class extends self.ITextInstance {},
	PlayJg: class extends self.IButtonInstance {},
	tuturial: class extends self.IButtonInstance {},
	Sprite2: class extends self.ISpriteInstance {},
	Sprite3: class extends self.ISpriteInstance {},
	Sprite4: class extends self.ISpriteInstance {},
	Texto2: class extends self.ITextInstance {},
	Jogar: class extends self.IButtonInstance {},
	Sprite5: class extends self.ISpriteInstance {},
	Texto3: class extends self.ITextInstance {},
	Texto4: class extends self.ITextInstance {},
	Texto5: class extends self.ITextInstance {},
	ERRADADA1: class extends self.ITextInstance {},
	CERTADA1: class extends self.ITextInstance {},
	Sprite6: class extends self.ISpriteInstance {},
	Sprite7: class extends self.ISpriteInstance {},
	Sprite8: class extends self.ISpriteInstance {},
	Sprite9: class extends self.ISpriteInstance {},
	Texto6: class extends self.ITextInstance {},
	Texto7: class extends self.ITextInstance {},
	VOLTAR: class extends self.IButtonInstance {},
	Sprite10: class extends self.ISpriteInstance {},
	Texto8: class extends self.ITextInstance {},
	Texto9: class extends self.ITextInstance {},
	NIKE: class extends self.ISpriteInstance {},
	Sprite11: class extends self.ISpriteInstance {},
	Texto10: class extends self.ITextInstance {},
	ERRADODA2: class extends self.ITextInstance {},
	CORRETADA2: class extends self.ITextInstance {},
	Sprite12: class extends self.ISpriteInstance {},
	Texto11: class extends self.ITextInstance {},
	Sprite13: class extends self.ISpriteInstance {},
	Texto12: class extends self.ITextInstance {},
	TRANSIÇÃO: class extends self.IButtonInstance {},
	Botão2: class extends self.IButtonInstance {},
	Sprite14: class extends self.ISpriteInstance {},
	Sprite15: class extends self.ISpriteInstance {},
	Texto13: class extends self.ITextInstance {},
	Texto14: class extends self.ITextInstance {},
	Texto15: class extends self.ITextInstance {},
	FLOR: class extends self.ISpriteInstance {},
	Sprite16: class extends self.ISpriteInstance {},
	Texto16: class extends self.ITextInstance {},
	Sprite17: class extends self.ISpriteInstance {},
	bolinha: class extends self.ISpriteInstance {},
	Sprite18: class extends self.ISpriteInstance {},
	ney: class extends self.ISpriteInstance {},
	Sprite20: class extends self.ISpriteInstance {},
	Teclado: class extends self.IInstance {},
	Sprite19: class extends self.ISpriteInstance {},
	gira: class extends self.ISpriteInstance {},
	Sprite21: class extends self.ISpriteInstance {},
	Sprite22: class extends self.ISpriteInstance {},
	Sprite23: class extends self.ISpriteInstance {},
	Sprite24: class extends self.ISpriteInstance {},
	Texto17: class extends self.ITextInstance {},
	Texto18: class extends self.ITextInstance {},
	laele: class extends self.ISpriteInstance {}
}