const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Plugins.Mouse,
		C3.Plugins.Text,
		C3.Behaviors.Sin,
		C3.Plugins.Mouse.Cnds.OnObjectClicked,
		C3.Plugins.System.Acts.GoToLayout
	];
};
self.C3_JsPropNameTable = [
	{dragonballzsuper2560x: 0},
	{Dragon_Ball_Z_Logo_A: 0},
	{Mouse: 0},
	{bcomeço: 0},
	{texto1: 0},
	{x1080desktopfullhddragonballzabridgedbackgroundphoto: 0},
	{btutorial: 0},
	{tutorial: 0},
	{ttutorial: 0},
	{nada: 0},
	{nada2: 0},
	{setanada: 0},
	{voltarComeço: 0},
	{rightarrow_: 0},
	{Sprite: 0},
	{Senóide: 0},
	{Texto: 0},
	{p1certa: 0},
	{Texto2: 0},
	{errada: 0},
	{Texto3: 0},
	{dwr5pt58e147cb42a84daa9fba855e665120f: 0},
	{dwr5pt58e147cb42a84daa9fba855e665120f5removebgpreview: 0},
	{Black_render: 0},
	{p2acerto: 0},
	{b22f1fa3b9cea39727b1ed97removebgpreview: 0},
	{Sprite2: 0},
	{p3certa: 0},
	{pngclipartgogetagokuvegetadragonballfighterzgohangokufictionalcharactercartoon: 0},
	{pngclipartgogetagokuvegetadragonballfighterzgohangokufictionalcharactercartoonremovebgpreview: 0},
	{p4acerta: 0},
	{f62f29c1fc346a0df1f173be3ad4e638removebgpreview: 0},
	{p5acerta: 0},
	{Texto4: 0},
	{pvitoria: 0},
	{Gohan: 0},
	{pderrota: 0},
	{Texto5: 0}
];

self.InstanceType = {
	dragonballzsuper2560x: class extends self.ISpriteInstance {},
	Dragon_Ball_Z_Logo_A: class extends self.ISpriteInstance {},
	Mouse: class extends self.IInstance {},
	bcomeço: class extends self.ISpriteInstance {},
	texto1: class extends self.ITextInstance {},
	x1080desktopfullhddragonballzabridgedbackgroundphoto: class extends self.ISpriteInstance {},
	btutorial: class extends self.ISpriteInstance {},
	tutorial: class extends self.ITextInstance {},
	ttutorial: class extends self.ITextInstance {},
	nada: class extends self.ISpriteInstance {},
	nada2: class extends self.ITextInstance {},
	setanada: class extends self.ISpriteInstance {},
	voltarComeço: class extends self.ISpriteInstance {},
	rightarrow_: class extends self.ISpriteInstance {},
	Sprite: class extends self.ISpriteInstance {},
	Texto: class extends self.ITextInstance {},
	p1certa: class extends self.ISpriteInstance {},
	Texto2: class extends self.ITextInstance {},
	errada: class extends self.ISpriteInstance {},
	Texto3: class extends self.ITextInstance {},
	dwr5pt58e147cb42a84daa9fba855e665120f: class extends self.ISpriteInstance {},
	dwr5pt58e147cb42a84daa9fba855e665120f5removebgpreview: class extends self.ISpriteInstance {},
	Black_render: class extends self.ISpriteInstance {},
	p2acerto: class extends self.ISpriteInstance {},
	b22f1fa3b9cea39727b1ed97removebgpreview: class extends self.ISpriteInstance {},
	Sprite2: class extends self.ISpriteInstance {},
	p3certa: class extends self.ISpriteInstance {},
	pngclipartgogetagokuvegetadragonballfighterzgohangokufictionalcharactercartoon: class extends self.ISpriteInstance {},
	pngclipartgogetagokuvegetadragonballfighterzgohangokufictionalcharactercartoonremovebgpreview: class extends self.ISpriteInstance {},
	p4acerta: class extends self.ISpriteInstance {},
	f62f29c1fc346a0df1f173be3ad4e638removebgpreview: class extends self.ISpriteInstance {},
	p5acerta: class extends self.ISpriteInstance {},
	Texto4: class extends self.ITextInstance {},
	pvitoria: class extends self.ISpriteInstance {},
	Gohan: class extends self.ISpriteInstance {},
	pderrota: class extends self.ISpriteInstance {},
	Texto5: class extends self.ITextInstance {}
}